'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5456.
'
Namespace JXChange20111.Image
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ImageServiceSoapBinding", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class ImageServiceWse
        Inherits Microsoft.Web.Services3.WebservicesClientProtocol
        
        Private PingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChkImgInqOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DocImgAddOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DocImgSrchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.JXChange20111_JXChange20111_Image_ImageService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event PingCompleted As PingCompletedEventHandler
        
        '''<remarks/>
        Public Event ChkImgInqCompleted As ChkImgInqCompletedEventHandler
        
        '''<remarks/>
        Public Event DocImgAddCompleted As DocImgAddCompletedEventHandler
        
        '''<remarks/>
        Public Event DocImgSrchCompleted As DocImgSrchCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jackhenry.com/ws/Ping", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function Ping(<System.Xml.Serialization.XmlElementAttribute("Ping", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> ByVal Ping1 As PingRq_MType) As <System.Xml.Serialization.XmlElementAttribute("PingResponse", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> PingRs_MType
            Dim results() As Object = Me.Invoke("Ping", New Object() {Ping1})
            Return CType(results(0),PingRs_MType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PingAsync(ByVal Ping1 As PingRq_MType)
            Me.PingAsync(Ping1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PingAsync(ByVal Ping1 As PingRq_MType, ByVal userState As Object)
            If (Me.PingOperationCompleted Is Nothing) Then
                Me.PingOperationCompleted = AddressOf Me.OnPingOperationCompleted
            End If
            Me.InvokeAsync("Ping", New Object() {Ping1}, Me.PingOperationCompleted, userState)
        End Sub
        
        Private Sub OnPingOperationCompleted(ByVal arg As Object)
            If (Not (Me.PingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PingCompleted(Me, New PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jackhenry.com/ws/ChkImgInq", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ChkImgInq(<System.Xml.Serialization.XmlElementAttribute("ChkImgInq", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> ByVal ChkImgInq1 As ChkImgInqRq_MType) As <System.Xml.Serialization.XmlElementAttribute("ChkImgInqResponse", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> ChkImgInqRs_MType
            Dim results() As Object = Me.Invoke("ChkImgInq", New Object() {ChkImgInq1})
            Return CType(results(0),ChkImgInqRs_MType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChkImgInqAsync(ByVal ChkImgInq1 As ChkImgInqRq_MType)
            Me.ChkImgInqAsync(ChkImgInq1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChkImgInqAsync(ByVal ChkImgInq1 As ChkImgInqRq_MType, ByVal userState As Object)
            If (Me.ChkImgInqOperationCompleted Is Nothing) Then
                Me.ChkImgInqOperationCompleted = AddressOf Me.OnChkImgInqOperationCompleted
            End If
            Me.InvokeAsync("ChkImgInq", New Object() {ChkImgInq1}, Me.ChkImgInqOperationCompleted, userState)
        End Sub
        
        Private Sub OnChkImgInqOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChkImgInqCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChkImgInqCompleted(Me, New ChkImgInqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jackhenry.com/ws/DocImgAdd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function DocImgAdd(<System.Xml.Serialization.XmlElementAttribute("DocImgAdd", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> ByVal DocImgAdd1 As DocImgAddRq_MType) As <System.Xml.Serialization.XmlElementAttribute("DocImgAddResponse", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> DocImgAddRs_MType
            Dim results() As Object = Me.Invoke("DocImgAdd", New Object() {DocImgAdd1})
            Return CType(results(0),DocImgAddRs_MType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DocImgAddAsync(ByVal DocImgAdd1 As DocImgAddRq_MType)
            Me.DocImgAddAsync(DocImgAdd1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DocImgAddAsync(ByVal DocImgAdd1 As DocImgAddRq_MType, ByVal userState As Object)
            If (Me.DocImgAddOperationCompleted Is Nothing) Then
                Me.DocImgAddOperationCompleted = AddressOf Me.OnDocImgAddOperationCompleted
            End If
            Me.InvokeAsync("DocImgAdd", New Object() {DocImgAdd1}, Me.DocImgAddOperationCompleted, userState)
        End Sub
        
        Private Sub OnDocImgAddOperationCompleted(ByVal arg As Object)
            If (Not (Me.DocImgAddCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DocImgAddCompleted(Me, New DocImgAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jackhenry.com/ws/DocImgSrch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function DocImgSrch(<System.Xml.Serialization.XmlElementAttribute("DocImgSrch", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> ByVal DocImgSrch1 As DocImgSrchRq_MType) As <System.Xml.Serialization.XmlElementAttribute("DocImgSrchResponse", [Namespace]:="http://jackhenry.com/jxchange/TPG/2008")> DocImgSrchRs_MType
            Dim results() As Object = Me.Invoke("DocImgSrch", New Object() {DocImgSrch1})
            Return CType(results(0),DocImgSrchRs_MType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DocImgSrchAsync(ByVal DocImgSrch1 As DocImgSrchRq_MType)
            Me.DocImgSrchAsync(DocImgSrch1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DocImgSrchAsync(ByVal DocImgSrch1 As DocImgSrchRq_MType, ByVal userState As Object)
            If (Me.DocImgSrchOperationCompleted Is Nothing) Then
                Me.DocImgSrchOperationCompleted = AddressOf Me.OnDocImgSrchOperationCompleted
            End If
            Me.InvokeAsync("DocImgSrch", New Object() {DocImgSrch1}, Me.DocImgSrchOperationCompleted, userState)
        End Sub
        
        Private Sub OnDocImgSrchOperationCompleted(ByVal arg As Object)
            If (Not (Me.DocImgSrchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DocImgSrchCompleted(Me, New DocImgSrchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class PingRq_MType
        
        Private pingRqField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property PingRq() As String
            Get
                Return Me.pingRqField
            End Get
            Set
                Me.pingRqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class Ver_1_CType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgSrchInfo_CType
        
        Private docNameField As String
        
        Private docImgIdxArrayField() As DocImgIdx_CType
        
        Private docImgDetArrayField() As DocImgDetInfo_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property DocName() As String
            Get
                Return Me.docNameField
            End Get
            Set
                Me.docNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocImgIdx", IsNullable:=false)>  _
        Public Property DocImgIdxArray() As DocImgIdx_CType()
            Get
                Return Me.docImgIdxArrayField
            End Get
            Set
                Me.docImgIdxArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocImgDetInfo", IsNullable:=false)>  _
        Public Property DocImgDetArray() As DocImgDetInfo_CType()
            Get
                Return Me.docImgDetArrayField
            End Get
            Set
                Me.docImgDetArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgIdx_CType
        
        Private docImgIdxNameField As String
        
        Private docImgIdxTypeField As String
        
        Private docImgIdxValueField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property DocImgIdxName() As String
            Get
                Return Me.docImgIdxNameField
            End Get
            Set
                Me.docImgIdxNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocImgIdxType() As String
            Get
                Return Me.docImgIdxTypeField
            End Get
            Set
                Me.docImgIdxTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocImgIdxValue() As String
            Get
                Return Me.docImgIdxValueField
            End Get
            Set
                Me.docImgIdxValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgDetInfo_CType
        
        Private docImgField() As Byte
        
        Private docImgSizeField As Integer
        
        Private docImgSizeFieldSpecified As Boolean
        
        Private docImgProcSeqField As Integer
        
        Private docImgProcSeqFieldSpecified As Boolean
        
        Private docImgFormatField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property DocImg() As Byte()
            Get
                Return Me.docImgField
            End Get
            Set
                Me.docImgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocImgSize() As Integer
            Get
                Return Me.docImgSizeField
            End Get
            Set
                Me.docImgSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DocImgSizeSpecified() As Boolean
            Get
                Return Me.docImgSizeFieldSpecified
            End Get
            Set
                Me.docImgSizeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocImgProcSeq() As Integer
            Get
                Return Me.docImgProcSeqField
            End Get
            Set
                Me.docImgProcSeqField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DocImgProcSeqSpecified() As Boolean
            Get
                Return Me.docImgProcSeqFieldSpecified
            End Get
            Set
                Me.docImgProcSeqFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocImgFormat() As String
            Get
                Return Me.docImgFormatField
            End Get
            Set
                Me.docImgFormatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class SrchMsgRsHdr_CType
        
        Private jXchangeHdrField As jXchangeHdr_CType
        
        Private sentRecField As Integer
        
        Private sentRecFieldSpecified As Boolean
        
        Private moreRecField As String
        
        Private cursorField As String
        
        Private totRecField As Integer
        
        Private totRecFieldSpecified As Boolean
        
        Private msgRecInfoArrayField() As MsgRec_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property jXchangeHdr() As jXchangeHdr_CType
            Get
                Return Me.jXchangeHdrField
            End Get
            Set
                Me.jXchangeHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SentRec() As Integer
            Get
                Return Me.sentRecField
            End Get
            Set
                Me.sentRecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SentRecSpecified() As Boolean
            Get
                Return Me.sentRecFieldSpecified
            End Get
            Set
                Me.sentRecFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MoreRec() As String
            Get
                Return Me.moreRecField
            End Get
            Set
                Me.moreRecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cursor() As String
            Get
                Return Me.cursorField
            End Get
            Set
                Me.cursorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotRec() As Integer
            Get
                Return Me.totRecField
            End Get
            Set
                Me.totRecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TotRecSpecified() As Boolean
            Get
                Return Me.totRecFieldSpecified
            End Get
            Set
                Me.totRecFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("MsgRec", IsNullable:=false)>  _
        Public Property MsgRecInfoArray() As MsgRec_CType()
            Get
                Return Me.msgRecInfoArrayField
            End Get
            Set
                Me.msgRecInfoArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class jXchangeHdr_CType
        
        Private jxVerField As String
        
        Private auditUsrIdField As String
        
        Private auditWsIdField As String
        
        Private authenUsrIdField As String
        
        Private consumerNameField As String
        
        Private consumerProdField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private jXLogTrackingIdField As String
        
        Private ver_2Field As Ver_2_CType
        
        Private instRtIdField As String
        
        Private instEnvField As String
        
        Private ver_3Field As Ver_3_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property JxVer() As String
            Get
                Return Me.jxVerField
            End Get
            Set
                Me.jxVerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuditUsrId() As String
            Get
                Return Me.auditUsrIdField
            End Get
            Set
                Me.auditUsrIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuditWsId() As String
            Get
                Return Me.auditWsIdField
            End Get
            Set
                Me.auditWsIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuthenUsrId() As String
            Get
                Return Me.authenUsrIdField
            End Get
            Set
                Me.authenUsrIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsumerName() As String
            Get
                Return Me.consumerNameField
            End Get
            Set
                Me.consumerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsumerProd() As String
            Get
                Return Me.consumerProdField
            End Get
            Set
                Me.consumerProdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property jXLogTrackingId() As String
            Get
                Return Me.jXLogTrackingIdField
            End Get
            Set
                Me.jXLogTrackingIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_2() As Ver_2_CType
            Get
                Return Me.ver_2Field
            End Get
            Set
                Me.ver_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InstRtId() As String
            Get
                Return Me.instRtIdField
            End Get
            Set
                Me.instRtIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InstEnv() As String
            Get
                Return Me.instEnvField
            End Get
            Set
                Me.instEnvField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_3() As Ver_3_CType
            Get
                Return Me.ver_3Field
            End Get
            Set
                Me.ver_3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class Ver_2_CType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class Ver_3_CType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class MsgRec_CType
        
        Private errCodeField As String
        
        Private errCatField As String
        
        Private errDescField As String
        
        Private errElemField As String
        
        Private errElemValField As String
        
        Private errLocField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property ErrCode() As String
            Get
                Return Me.errCodeField
            End Get
            Set
                Me.errCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrCat() As String
            Get
                Return Me.errCatField
            End Get
            Set
                Me.errCatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrDesc() As String
            Get
                Return Me.errDescField
            End Get
            Set
                Me.errDescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrElem() As String
            Get
                Return Me.errElemField
            End Get
            Set
                Me.errElemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrElemVal() As String
            Get
                Return Me.errElemValField
            End Get
            Set
                Me.errElemValField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrLoc() As String
            Get
                Return Me.errLocField
            End Get
            Set
                Me.errLocField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgSrchRs_MType
        
        Private srchMsgRsHdrField As SrchMsgRsHdr_CType
        
        Private idxOnlyField As String
        
        Private docImgSrchArrayField() As DocImgSrchInfo_CType
        
        Private customField As Custom_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private docImgFilterTypeField As String
        
        Private ver_2Field As Ver_2_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property SrchMsgRsHdr() As SrchMsgRsHdr_CType
            Get
                Return Me.srchMsgRsHdrField
            End Get
            Set
                Me.srchMsgRsHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdxOnly() As String
            Get
                Return Me.idxOnlyField
            End Get
            Set
                Me.idxOnlyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("DocImgSrchInfo", IsNullable:=false)>  _
        Public Property DocImgSrchArray() As DocImgSrchInfo_CType()
            Get
                Return Me.docImgSrchArrayField
            End Get
            Set
                Me.docImgSrchArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Custom() As Custom_CType
            Get
                Return Me.customField
            End Get
            Set
                Me.customField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DocImgFilterType() As String
            Get
                Return Me.docImgFilterTypeField
            End Get
            Set
                Me.docImgFilterTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_2() As Ver_2_CType
            Get
                Return Me.ver_2Field
            End Get
            Set
                Me.ver_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class Custom_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class SrchMsgRqHdr_CType
        
        Private jXchangeHdrField As jXchangeHdr_CType
        
        Private maxRecField As Integer
        
        Private cursorField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private authenUsrCredField As AuthenUsrCred_CType
        
        Private ver_2Field As Ver_2_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property jXchangeHdr() As jXchangeHdr_CType
            Get
                Return Me.jXchangeHdrField
            End Get
            Set
                Me.jXchangeHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaxRec() As Integer
            Get
                Return Me.maxRecField
            End Get
            Set
                Me.maxRecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cursor() As String
            Get
                Return Me.cursorField
            End Get
            Set
                Me.cursorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuthenUsrCred() As AuthenUsrCred_CType
            Get
                Return Me.authenUsrCredField
            End Get
            Set
                Me.authenUsrCredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_2() As Ver_2_CType
            Get
                Return Me.ver_2Field
            End Get
            Set
                Me.ver_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class AuthenUsrCred_CType
        
        Private securityField As SecurityHeaderType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"& _ 
            "")>  _
        Public Property Security() As SecurityHeaderType
            Get
                Return Me.securityField
            End Get
            Set
                Me.securityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"& _ 
        "")>  _
    Partial Public Class SecurityHeaderType
        
        Private anyField() As System.Xml.XmlElement
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgSrchRq_MType
        
        Private srchMsgRqHdrField As SrchMsgRqHdr_CType
        
        Private docImgIdxArrayField() As DocImgIdx_CType
        
        Private idxOnlyField As String
        
        Private customField As Custom_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private docImgFilterTypeField As String
        
        Private ver_2Field As Ver_2_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property SrchMsgRqHdr() As SrchMsgRqHdr_CType
            Get
                Return Me.srchMsgRqHdrField
            End Get
            Set
                Me.srchMsgRqHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocImgIdx", IsNullable:=false)>  _
        Public Property DocImgIdxArray() As DocImgIdx_CType()
            Get
                Return Me.docImgIdxArrayField
            End Get
            Set
                Me.docImgIdxArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IdxOnly() As String
            Get
                Return Me.idxOnlyField
            End Get
            Set
                Me.idxOnlyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Custom() As Custom_CType
            Get
                Return Me.customField
            End Get
            Set
                Me.customField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DocImgFilterType() As String
            Get
                Return Me.docImgFilterTypeField
            End Get
            Set
                Me.docImgFilterTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_2() As Ver_2_CType
            Get
                Return Me.ver_2Field
            End Get
            Set
                Me.ver_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgInfoRs_CType
        
        Private docNameField As String
        
        Private docImgIdxArrayField() As DocImgIdx_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property DocName() As String
            Get
                Return Me.docNameField
            End Get
            Set
                Me.docNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocImgIdx", IsNullable:=false)>  _
        Public Property DocImgIdxArray() As DocImgIdx_CType()
            Get
                Return Me.docImgIdxArrayField
            End Get
            Set
                Me.docImgIdxArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgAddRs_MType
        
        Private msgRsHdrField As MsgRsHdr_CType
        
        Private docImgInfoRsArrayField() As DocImgInfoRs_CType
        
        Private rsStatField As String
        
        Private customField As Custom_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property MsgRsHdr() As MsgRsHdr_CType
            Get
                Return Me.msgRsHdrField
            End Get
            Set
                Me.msgRsHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("DocImgInfoRs", IsNullable:=false)>  _
        Public Property DocImgInfoRsArray() As DocImgInfoRs_CType()
            Get
                Return Me.docImgInfoRsArrayField
            End Get
            Set
                Me.docImgInfoRsArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RsStat() As String
            Get
                Return Me.rsStatField
            End Get
            Set
                Me.rsStatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Custom() As Custom_CType
            Get
                Return Me.customField
            End Get
            Set
                Me.customField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class MsgRsHdr_CType
        
        Private jXchangeHdrField As jXchangeHdr_CType
        
        Private msgRecInfoArrayField() As MsgRec_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property jXchangeHdr() As jXchangeHdr_CType
            Get
                Return Me.jXchangeHdrField
            End Get
            Set
                Me.jXchangeHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("MsgRec", IsNullable:=false)>  _
        Public Property MsgRecInfoArray() As MsgRec_CType()
            Get
                Return Me.msgRecInfoArrayField
            End Get
            Set
                Me.msgRecInfoArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgInfo_CType
        
        Private docNameField As String
        
        Private docImgAuxDescField As String
        
        Private docImgEffDtField As Date
        
        Private docImgEffDtFieldSpecified As Boolean
        
        Private docImgDetArrayField() As DocImgDetInfo_CType
        
        Private docImgIdxArrayField() As DocImgIdx_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property DocName() As String
            Get
                Return Me.docNameField
            End Get
            Set
                Me.docNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocImgAuxDesc() As String
            Get
                Return Me.docImgAuxDescField
            End Get
            Set
                Me.docImgAuxDescField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DocImgEffDt() As Date
            Get
                Return Me.docImgEffDtField
            End Get
            Set
                Me.docImgEffDtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DocImgEffDtSpecified() As Boolean
            Get
                Return Me.docImgEffDtFieldSpecified
            End Get
            Set
                Me.docImgEffDtFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocImgDetInfo", IsNullable:=false)>  _
        Public Property DocImgDetArray() As DocImgDetInfo_CType()
            Get
                Return Me.docImgDetArrayField
            End Get
            Set
                Me.docImgDetArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocImgIdx", IsNullable:=false)>  _
        Public Property DocImgIdxArray() As DocImgIdx_CType()
            Get
                Return Me.docImgIdxArrayField
            End Get
            Set
                Me.docImgIdxArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class ErrOvrRd_CType
        
        Private errCodeField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property ErrCode() As String
            Get
                Return Me.errCodeField
            End Get
            Set
                Me.errCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class DocImgAddRq_MType
        
        Private msgRqHdrField As MsgRqHdr_CType
        
        Private errOvrRdInfoArrayField() As ErrOvrRd_CType
        
        Private docImgInfoArrayField() As DocImgInfo_CType
        
        Private customField As Custom_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property MsgRqHdr() As MsgRqHdr_CType
            Get
                Return Me.msgRqHdrField
            End Get
            Set
                Me.msgRqHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("ErrOvrRd", IsNullable:=false)>  _
        Public Property ErrOvrRdInfoArray() As ErrOvrRd_CType()
            Get
                Return Me.errOvrRdInfoArrayField
            End Get
            Set
                Me.errOvrRdInfoArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocImgInfo", IsNullable:=false)>  _
        Public Property DocImgInfoArray() As DocImgInfo_CType()
            Get
                Return Me.docImgInfoArrayField
            End Get
            Set
                Me.docImgInfoArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Custom() As Custom_CType
            Get
                Return Me.customField
            End Get
            Set
                Me.customField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class MsgRqHdr_CType
        
        Private jXchangeHdrField As jXchangeHdr_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private authenUsrCredField As AuthenUsrCred_CType
        
        Private ver_2Field As Ver_2_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property jXchangeHdr() As jXchangeHdr_CType
            Get
                Return Me.jXchangeHdrField
            End Get
            Set
                Me.jXchangeHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuthenUsrCred() As AuthenUsrCred_CType
            Get
                Return Me.authenUsrCredField
            End Get
            Set
                Me.authenUsrCredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_2() As Ver_2_CType
            Get
                Return Me.ver_2Field
            End Get
            Set
                Me.ver_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class ChkImgInqRs_MType
        
        Private msgRsHdrField As MsgRsHdr_CType
        
        Private chkImgIdField As String
        
        Private chkImgFormatField As String
        
        Private chkImgSideField As String
        
        Private frontChkImgLengthField As System.Nullable(Of Integer)
        
        Private frontChkImgLengthFieldSpecified As Boolean
        
        Private frontChkImgField() As Byte
        
        Private backChkImgLengthField As System.Nullable(Of Integer)
        
        Private backChkImgLengthFieldSpecified As Boolean
        
        Private backChkImgField() As Byte
        
        Private customField As Custom_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property MsgRsHdr() As MsgRsHdr_CType
            Get
                Return Me.msgRsHdrField
            End Get
            Set
                Me.msgRsHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ChkImgId() As String
            Get
                Return Me.chkImgIdField
            End Get
            Set
                Me.chkImgIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ChkImgFormat() As String
            Get
                Return Me.chkImgFormatField
            End Get
            Set
                Me.chkImgFormatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ChkImgSide() As String
            Get
                Return Me.chkImgSideField
            End Get
            Set
                Me.chkImgSideField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FrontChkImgLength() As System.Nullable(Of Integer)
            Get
                Return Me.frontChkImgLengthField
            End Get
            Set
                Me.frontChkImgLengthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FrontChkImgLengthSpecified() As Boolean
            Get
                Return Me.frontChkImgLengthFieldSpecified
            End Get
            Set
                Me.frontChkImgLengthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property FrontChkImg() As Byte()
            Get
                Return Me.frontChkImgField
            End Get
            Set
                Me.frontChkImgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property BackChkImgLength() As System.Nullable(Of Integer)
            Get
                Return Me.backChkImgLengthField
            End Get
            Set
                Me.backChkImgLengthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property BackChkImgLengthSpecified() As Boolean
            Get
                Return Me.backChkImgLengthFieldSpecified
            End Get
            Set
                Me.backChkImgLengthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)>  _
        Public Property BackChkImg() As Byte()
            Get
                Return Me.backChkImgField
            End Get
            Set
                Me.backChkImgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Custom() As Custom_CType
            Get
                Return Me.customField
            End Get
            Set
                Me.customField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class ChkImgInqRq_MType
        
        Private msgRqHdrField As MsgRqHdr_CType
        
        Private chkImgIdField As String
        
        Private chkImgFormatField As String
        
        Private chkImgSideField As String
        
        Private customField As Custom_CType
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property MsgRqHdr() As MsgRqHdr_CType
            Get
                Return Me.msgRqHdrField
            End Get
            Set
                Me.msgRqHdrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ChkImgId() As String
            Get
                Return Me.chkImgIdField
            End Get
            Set
                Me.chkImgIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ChkImgFormat() As String
            Get
                Return Me.chkImgFormatField
            End Get
            Set
                Me.chkImgFormatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ChkImgSide() As String
            Get
                Return Me.chkImgSideField
            End Get
            Set
                Me.chkImgSideField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Custom() As Custom_CType
            Get
                Return Me.customField
            End Get
            Set
                Me.customField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://jackhenry.com/jxchange/TPG/2008")>  _
    Partial Public Class PingRs_MType
        
        Private pingRsField As String
        
        Private ver_1Field As Ver_1_CType
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        Public Property PingRs() As String
            Get
                Return Me.pingRsField
            End Get
            Set
                Me.pingRsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ver_1() As Ver_1_CType
            Get
                Return Me.ver_1Field
            End Get
            Set
                Me.ver_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub PingCompletedEventHandler(ByVal sender As Object, ByVal e As PingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PingRs_MType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PingRs_MType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub ChkImgInqCompletedEventHandler(ByVal sender As Object, ByVal e As ChkImgInqCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChkImgInqCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ChkImgInqRs_MType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ChkImgInqRs_MType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub DocImgAddCompletedEventHandler(ByVal sender As Object, ByVal e As DocImgAddCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DocImgAddCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocImgAddRs_MType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocImgAddRs_MType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub DocImgSrchCompletedEventHandler(ByVal sender As Object, ByVal e As DocImgSrchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DocImgSrchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocImgSrchRs_MType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocImgSrchRs_MType)
            End Get
        End Property
    End Class
End Namespace
