'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace AFCU2015_1.AccountCode
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AccountCode_MSSOAP_HTTP_Binding", [Namespace]:="http://americafirst.com/AccountCode")>  _
    Partial Public Class AccountCodeService
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        
        Private inquireAccountCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private inquireAccountCodeListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private maintainAccountCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private syncAccountCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.LoansPQWSWrappers_AFCU_AFCU2015_1_AccountCode_AccountCodeService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event inquireAccountCodeCompleted As inquireAccountCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event inquireAccountCodeListCompleted As inquireAccountCodeListCompletedEventHandler
        
        '''<remarks/>
        Public Event maintainAccountCodeCompleted As maintainAccountCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event syncAccountCodeCompleted As syncAccountCodeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function inquireAccountCode(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")> ByVal inquireAccountCodeRequest As InquireAccountCodeRequest) As <System.Xml.Serialization.XmlElementAttribute("accountCodeResponse", [Namespace]:="http://www.americafirst.com/20070315/AccountCode")> AccountCodeResponse
            Dim results() As Object = Me.Invoke("inquireAccountCode", New Object() {inquireAccountCodeRequest})
            Return CType(results(0),AccountCodeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub inquireAccountCodeAsync(ByVal inquireAccountCodeRequest As InquireAccountCodeRequest)
            Me.inquireAccountCodeAsync(inquireAccountCodeRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub inquireAccountCodeAsync(ByVal inquireAccountCodeRequest As InquireAccountCodeRequest, ByVal userState As Object)
            If (Me.inquireAccountCodeOperationCompleted Is Nothing) Then
                Me.inquireAccountCodeOperationCompleted = AddressOf Me.OninquireAccountCodeOperationCompleted
            End If
            Me.InvokeAsync("inquireAccountCode", New Object() {inquireAccountCodeRequest}, Me.inquireAccountCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OninquireAccountCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.inquireAccountCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent inquireAccountCodeCompleted(Me, New inquireAccountCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function inquireAccountCodeList(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")> ByVal inquireAccountCodeListRequest As InquireAccountCodeListRequest) As <System.Xml.Serialization.XmlElementAttribute("inquireAccountCodeListResponse", [Namespace]:="http://www.americafirst.com/20070315/AccountCode")> InquireAccountCodeListResponse
            Dim results() As Object = Me.Invoke("inquireAccountCodeList", New Object() {inquireAccountCodeListRequest})
            Return CType(results(0),InquireAccountCodeListResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub inquireAccountCodeListAsync(ByVal inquireAccountCodeListRequest As InquireAccountCodeListRequest)
            Me.inquireAccountCodeListAsync(inquireAccountCodeListRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub inquireAccountCodeListAsync(ByVal inquireAccountCodeListRequest As InquireAccountCodeListRequest, ByVal userState As Object)
            If (Me.inquireAccountCodeListOperationCompleted Is Nothing) Then
                Me.inquireAccountCodeListOperationCompleted = AddressOf Me.OninquireAccountCodeListOperationCompleted
            End If
            Me.InvokeAsync("inquireAccountCodeList", New Object() {inquireAccountCodeListRequest}, Me.inquireAccountCodeListOperationCompleted, userState)
        End Sub
        
        Private Sub OninquireAccountCodeListOperationCompleted(ByVal arg As Object)
            If (Not (Me.inquireAccountCodeListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent inquireAccountCodeListCompleted(Me, New inquireAccountCodeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function maintainAccountCode(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")> ByVal maintainAccountCodeRequest As MaintainAccountCodeRequest) As <System.Xml.Serialization.XmlElementAttribute("accountCodeResponse", [Namespace]:="http://www.americafirst.com/20070315/AccountCode")> AccountCodeResponse
            Dim results() As Object = Me.Invoke("maintainAccountCode", New Object() {maintainAccountCodeRequest})
            Return CType(results(0),AccountCodeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub maintainAccountCodeAsync(ByVal maintainAccountCodeRequest As MaintainAccountCodeRequest)
            Me.maintainAccountCodeAsync(maintainAccountCodeRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub maintainAccountCodeAsync(ByVal maintainAccountCodeRequest As MaintainAccountCodeRequest, ByVal userState As Object)
            If (Me.maintainAccountCodeOperationCompleted Is Nothing) Then
                Me.maintainAccountCodeOperationCompleted = AddressOf Me.OnmaintainAccountCodeOperationCompleted
            End If
            Me.InvokeAsync("maintainAccountCode", New Object() {maintainAccountCodeRequest}, Me.maintainAccountCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnmaintainAccountCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.maintainAccountCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent maintainAccountCodeCompleted(Me, New maintainAccountCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function syncAccountCode(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")> ByVal syncAccountCodeRequest As SyncAccountCodeRequest) As <System.Xml.Serialization.XmlElementAttribute("accountCodeResponse", [Namespace]:="http://www.americafirst.com/20070315/AccountCode")> AccountCodeResponse
            Dim results() As Object = Me.Invoke("syncAccountCode", New Object() {syncAccountCodeRequest})
            Return CType(results(0),AccountCodeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub syncAccountCodeAsync(ByVal syncAccountCodeRequest As SyncAccountCodeRequest)
            Me.syncAccountCodeAsync(syncAccountCodeRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub syncAccountCodeAsync(ByVal syncAccountCodeRequest As SyncAccountCodeRequest, ByVal userState As Object)
            If (Me.syncAccountCodeOperationCompleted Is Nothing) Then
                Me.syncAccountCodeOperationCompleted = AddressOf Me.OnsyncAccountCodeOperationCompleted
            End If
            Me.InvokeAsync("syncAccountCode", New Object() {syncAccountCodeRequest}, Me.syncAccountCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnsyncAccountCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.syncAccountCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent syncAccountCodeCompleted(Me, New syncAccountCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class InquireAccountCodeRequest
        
        Private headerField As AFCUHeaderRequest
        
        Private requestField As InquireAccountCode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderRequest
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property request() As InquireAccountCode
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Partial Public Class AFCUHeaderRequest
        
        Private processingDateField As Date
        
        Private companyIDField As String
        
        Private channelIDField As String
        
        Private branchIDField As String
        
        Private tellerIDField As String
        
        Private employeeIDField As String
        
        Private workstationIDField As String
        
        Private transactionIDField As String
        
        Private transactionRetryField As Boolean
        
        Private transactionRetryFieldSpecified As Boolean
        
        Private offlineIndicatorField As Boolean
        
        Private offlineIndicatorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
        Public Property processingDate() As Date
            Get
                Return Me.processingDateField
            End Get
            Set
                Me.processingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property companyID() As String
            Get
                Return Me.companyIDField
            End Get
            Set
                Me.companyIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property channelID() As String
            Get
                Return Me.channelIDField
            End Get
            Set
                Me.channelIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property branchID() As String
            Get
                Return Me.branchIDField
            End Get
            Set
                Me.branchIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property tellerID() As String
            Get
                Return Me.tellerIDField
            End Get
            Set
                Me.tellerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property employeeID() As String
            Get
                Return Me.employeeIDField
            End Get
            Set
                Me.employeeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property workstationID() As String
            Get
                Return Me.workstationIDField
            End Get
            Set
                Me.workstationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property transactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property transactionRetry() As Boolean
            Get
                Return Me.transactionRetryField
            End Get
            Set
                Me.transactionRetryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property transactionRetrySpecified() As Boolean
            Get
                Return Me.transactionRetryFieldSpecified
            End Get
            Set
                Me.transactionRetryFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property offlineIndicator() As Boolean
            Get
                Return Me.offlineIndicatorField
            End Get
            Set
                Me.offlineIndicatorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property offlineIndicatorSpecified() As Boolean
            Get
                Return Me.offlineIndicatorFieldSpecified
            End Get
            Set
                Me.offlineIndicatorFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class SyncAccountCode
        
        Private accountIDField As Long
        
        Private subAccountIDField As Integer
        
        Private subAccountIDFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property accountID() As Long
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAccountID() As Integer
            Get
                Return Me.subAccountIDField
            End Get
            Set
                Me.subAccountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property subAccountIDSpecified() As Boolean
            Get
                Return Me.subAccountIDFieldSpecified
            End Get
            Set
                Me.subAccountIDFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class SyncAccountCodeRequest
        
        Private headerField As AFCUHeaderRequest
        
        Private requestField As SyncAccountCode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderRequest
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property request() As SyncAccountCode
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class VendorAcctCategory
        
        Private acctCodeField As String
        
        Private subAcctCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property acctCode() As String
            Get
                Return Me.acctCodeField
            End Get
            Set
                Me.acctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAcctCode() As String
            Get
                Return Me.subAcctCodeField
            End Get
            Set
                Me.subAcctCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class AFCUAcctCategory
        
        Private acctCodeField As String
        
        Private subAcctCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property acctCode() As String
            Get
                Return Me.acctCodeField
            End Get
            Set
                Me.acctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAcctCode() As String
            Get
                Return Me.subAcctCodeField
            End Get
            Set
                Me.subAcctCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class MaintainAccountCode
        
        Private accountIDField As Long
        
        Private subAccountIDField As Integer
        
        Private subAccountIDFieldSpecified As Boolean
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property accountID() As Long
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAccountID() As Integer
            Get
                Return Me.subAccountIDField
            End Get
            Set
                Me.subAccountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property subAccountIDSpecified() As Boolean
            Get
                Return Me.subAccountIDFieldSpecified
            End Get
            Set
                Me.subAccountIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("acctCategory", GetType(AFCUAcctCategory), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("vendorAcctCategory", GetType(VendorAcctCategory), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class MaintainAccountCodeRequest
        
        Private headerField As AFCUHeaderRequest
        
        Private requestField As MaintainAccountCode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderRequest
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property request() As MaintainAccountCode
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class SubAccountCode
        
        Private subAcctCodeField As String
        
        Private subAcctDescriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAcctCode() As String
            Get
                Return Me.subAcctCodeField
            End Get
            Set
                Me.subAcctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAcctDescription() As String
            Get
                Return Me.subAcctDescriptionField
            End Get
            Set
                Me.subAcctDescriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class AccountCode
        
        Private acctCodeField As String
        
        Private acctDescriptionField As String
        
        Private subAccountCodesField() As SubAccountCode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property acctCode() As String
            Get
                Return Me.acctCodeField
            End Get
            Set
                Me.acctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property acctDescription() As String
            Get
                Return Me.acctDescriptionField
            End Get
            Set
                Me.acctDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("subAccountCode", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property subAccountCodes() As SubAccountCode()
            Get
                Return Me.subAccountCodesField
            End Get
            Set
                Me.subAccountCodesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class Response
        
        Private accountCodesField() As AccountCode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("accountCode", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property accountCodes() As AccountCode()
            Get
                Return Me.accountCodesField
            End Get
            Set
                Me.accountCodesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class InquireAccountCodeListResponse
        
        Private headerField As AFCUHeaderResponse
        
        Private responseField As Response
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderResponse
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property response() As Response
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Partial Public Class AFCUHeaderResponse
        
        Private systemResponseField() As SystemResponse
        
        Private resultField As Result
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("systemResponse", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property systemResponse() As SystemResponse()
            Get
                Return Me.systemResponseField
            End Get
            Set
                Me.systemResponseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property result() As Result
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Partial Public Class SystemResponse
        
        Private responseSourceField As String
        
        Private responseCodeField As String
        
        Private reasonCodeField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property responseSource() As String
            Get
                Return Me.responseSourceField
            End Get
            Set
                Me.responseSourceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property reasonCode() As String
            Get
                Return Me.reasonCodeField
            End Get
            Set
                Me.reasonCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Public Enum Result
        
        '''<remarks/>
        success
        
        '''<remarks/>
        failure
        
        '''<remarks/>
        warning
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class InquireAccountCodeListRequest
        
        Private headerField As AFCUHeaderRequest
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderRequest
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class AccountClassCode
        
        Private accountIDField As Long
        
        Private subAccountIDField As Integer
        
        Private subAccountIDFieldSpecified As Boolean
        
        Private acctCodeField As String
        
        Private subAcctCodeField As String
        
        Private acctDescField As String
        
        Private subAcctDescField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property accountID() As Long
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAccountID() As Integer
            Get
                Return Me.subAccountIDField
            End Get
            Set
                Me.subAccountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property subAccountIDSpecified() As Boolean
            Get
                Return Me.subAccountIDFieldSpecified
            End Get
            Set
                Me.subAccountIDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property acctCode() As String
            Get
                Return Me.acctCodeField
            End Get
            Set
                Me.acctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property subAcctCode() As String
            Get
                Return Me.subAcctCodeField
            End Get
            Set
                Me.subAcctCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property acctDesc() As String
            Get
                Return Me.acctDescField
            End Get
            Set
                Me.acctDescField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property subAcctDesc() As String
            Get
                Return Me.subAcctDescField
            End Get
            Set
                Me.subAcctDescField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class AccountCodeResponse
        
        Private headerField As AFCUHeaderResponse
        
        Private responseField As AccountClassCode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderResponse
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property response() As AccountClassCode
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AccountCode")>  _
    Partial Public Class InquireAccountCode
        
        Private accountIDField As Long
        
        Private subAccountIDField As Integer
        
        Private subAccountIDFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property accountID() As Long
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subAccountID() As Integer
            Get
                Return Me.subAccountIDField
            End Get
            Set
                Me.subAccountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property subAccountIDSpecified() As Boolean
            Get
                Return Me.subAccountIDFieldSpecified
            End Get
            Set
                Me.subAccountIDFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub inquireAccountCodeCompletedEventHandler(ByVal sender As Object, ByVal e As inquireAccountCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class inquireAccountCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AccountCodeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AccountCodeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub inquireAccountCodeListCompletedEventHandler(ByVal sender As Object, ByVal e As inquireAccountCodeListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class inquireAccountCodeListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InquireAccountCodeListResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InquireAccountCodeListResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub maintainAccountCodeCompletedEventHandler(ByVal sender As Object, ByVal e As maintainAccountCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class maintainAccountCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AccountCodeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AccountCodeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub syncAccountCodeCompletedEventHandler(ByVal sender As Object, ByVal e As syncAccountCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class syncAccountCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AccountCodeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AccountCodeResponse)
            End Get
        End Property
    End Class
End Namespace
