'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5472
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5472.
'
Namespace ConnectWare.DepositAccountInquiry
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="mtvnCWDPAcctInqWSV8", [Namespace]:="mtvnDPAcctInqWSV8")>  _
    Partial Public Class mtvnCWDPAcctInqWSV8
		Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        
        Private DPAcctInqOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.LoansPQWSWrappers_ConnectWare_ConnectWare_DepositAccountInquiry_mtvnCWDPAcctInqWSV8
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event DPAcctInqCompleted As DPAcctInqCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("DPAcctInqWSV8:DPAcctInqMtvnSvcReqMsg", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function DPAcctInq(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="mtvnCWDPAcctInqSvcReq")> ByVal DPAcctInqMtvnSvcReq As DPAcctInqMtvnSvcReq) As <System.Xml.Serialization.XmlElementAttribute("DPAcctInqMtvnSvcRes", [Namespace]:="mtvnCWDPAcctInqSvcRes")> DPAcctInqMtvnSvcRes
            Dim results() As Object = Me.Invoke("DPAcctInq", New Object() {DPAcctInqMtvnSvcReq})
            Return CType(results(0),DPAcctInqMtvnSvcRes)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DPAcctInqAsync(ByVal DPAcctInqMtvnSvcReq As DPAcctInqMtvnSvcReq)
            Me.DPAcctInqAsync(DPAcctInqMtvnSvcReq, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DPAcctInqAsync(ByVal DPAcctInqMtvnSvcReq As DPAcctInqMtvnSvcReq, ByVal userState As Object)
            If (Me.DPAcctInqOperationCompleted Is Nothing) Then
                Me.DPAcctInqOperationCompleted = AddressOf Me.OnDPAcctInqOperationCompleted
            End If
            Me.InvokeAsync("DPAcctInq", New Object() {DPAcctInqMtvnSvcReq}, Me.DPAcctInqOperationCompleted, userState)
        End Sub
        
        Private Sub OnDPAcctInqOperationCompleted(ByVal arg As Object)
            If (Not (Me.DPAcctInqCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DPAcctInqCompleted(Me, New DPAcctInqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReq
        
        Private mtvnSvcVerField As DPAcctInqMtvnSvcReqMtvnSvcVer
        
        Private msgUUIDField As String
        
        Private prcsParmsField As DPAcctInqMtvnSvcReqPrcsParms
        
        Private svcField() As DPAcctInqMtvnSvcReqSvc
        
        '''<remarks/>
        Public Property MtvnSvcVer() As DPAcctInqMtvnSvcReqMtvnSvcVer
            Get
                Return Me.mtvnSvcVerField
            End Get
            Set
                Me.mtvnSvcVerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MsgUUID() As String
            Get
                Return Me.msgUUIDField
            End Get
            Set
                Me.msgUUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrcsParms() As DPAcctInqMtvnSvcReqPrcsParms
            Get
                Return Me.prcsParmsField
            End Get
            Set
                Me.prcsParmsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Svc")>  _
        Public Property Svc() As DPAcctInqMtvnSvcReqSvc()
            Get
                Return Me.svcField
            End Get
            Set
                Me.svcField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Public Enum DPAcctInqMtvnSvcReqMtvnSvcVer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1.0")>  _
        Item10
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqPrcsParms
        
        Private srcIDField As String
        
        Private testIndField As String
        
        '''<remarks/>
        Public Property SrcID() As String
            Get
                Return Me.srcIDField
            End Get
            Set
                Me.srcIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TestInd() As String
            Get
                Return Me.testIndField
            End Get
            Set
                Me.testIndField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvc
        
        Private svcParmsField As DPAcctInqMtvnSvcReqSvcSvcParms
        
        Private securityField As DPAcctInqMtvnSvcReqSvcSecurity
        
        Private msgDataField As DPAcctInqMtvnSvcReqSvcMsgData
        
        '''<remarks/>
        Public Property SvcParms() As DPAcctInqMtvnSvcReqSvcSvcParms
            Get
                Return Me.svcParmsField
            End Get
            Set
                Me.svcParmsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Security() As DPAcctInqMtvnSvcReqSvcSecurity
            Get
                Return Me.securityField
            End Get
            Set
                Me.securityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MsgData() As DPAcctInqMtvnSvcReqSvcMsgData
            Get
                Return Me.msgDataField
            End Get
            Set
                Me.msgDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcSvcParms
        
        Private applIDField As DPAcctInqMtvnSvcReqSvcSvcParmsApplID
        
        Private svcIDField As DPAcctInqMtvnSvcReqSvcSvcParmsSvcID
        
        Private svcVerField As DPAcctInqMtvnSvcReqSvcSvcParmsSvcVer
        
        Private svcNmeField As String
        
        Private rqstUUIDField As String
        
        Private routingIDField As String
        
        Private srcField As DPAcctInqMtvnSvcReqSvcSvcParmsSrc
        
        '''<remarks/>
        Public Property ApplID() As DPAcctInqMtvnSvcReqSvcSvcParmsApplID
            Get
                Return Me.applIDField
            End Get
            Set
                Me.applIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SvcID() As DPAcctInqMtvnSvcReqSvcSvcParmsSvcID
            Get
                Return Me.svcIDField
            End Get
            Set
                Me.svcIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SvcVer() As DPAcctInqMtvnSvcReqSvcSvcParmsSvcVer
            Get
                Return Me.svcVerField
            End Get
            Set
                Me.svcVerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SvcNme() As String
            Get
                Return Me.svcNmeField
            End Get
            Set
                Me.svcNmeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RqstUUID() As String
            Get
                Return Me.rqstUUIDField
            End Get
            Set
                Me.rqstUUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RoutingID() As String
            Get
                Return Me.routingIDField
            End Get
            Set
                Me.routingIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Src() As DPAcctInqMtvnSvcReqSvcSvcParmsSrc
            Get
                Return Me.srcField
            End Get
            Set
                Me.srcField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Public Enum DPAcctInqMtvnSvcReqSvcSvcParmsApplID
        
        '''<remarks/>
        DP
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Public Enum DPAcctInqMtvnSvcReqSvcSvcParmsSvcID
        
        '''<remarks/>
        DPAcctInq
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Public Enum DPAcctInqMtvnSvcReqSvcSvcParmsSvcVer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("8.0")>  _
        Item80
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcSvcParmsSrc
        
        Private fieldListField() As DPAcctInqMtvnSvcReqSvcSvcParmsSrcField
        
        Private grpBusFuncField As String
        
        Private tranInfoField As String
        
        Private custDefMsgSrc1Field As String
        
        Private custDefMsgSrc2Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable:=false)>  _
        Public Property FieldList() As DPAcctInqMtvnSvcReqSvcSvcParmsSrcField()
            Get
                Return Me.fieldListField
            End Get
            Set
                Me.fieldListField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GrpBusFunc() As String
            Get
                Return Me.grpBusFuncField
            End Get
            Set
                Me.grpBusFuncField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TranInfo() As String
            Get
                Return Me.tranInfoField
            End Get
            Set
                Me.tranInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustDefMsgSrc1() As String
            Get
                Return Me.custDefMsgSrc1Field
            End Get
            Set
                Me.custDefMsgSrc1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustDefMsgSrc2() As String
            Get
                Return Me.custDefMsgSrc2Field
            End Get
            Set
                Me.custDefMsgSrc2Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcSvcParmsSrcField
        
        Private fieldNmeField As String
        
        Private fieldValField As String
        
        '''<remarks/>
        Public Property FieldNme() As String
            Get
                Return Me.fieldNmeField
            End Get
            Set
                Me.fieldNmeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldVal() As String
            Get
                Return Me.fieldValField
            End Get
            Set
                Me.fieldValField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcSecurity
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("BasicAuth", GetType(DPAcctInqMtvnSvcReqSvcSecurityBasicAuth)),  _
         System.Xml.Serialization.XmlElementAttribute("NoAuth", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("SAMLAuth", GetType(DPAcctInqMtvnSvcReqSvcSecuritySAMLAuth)),  _
         System.Xml.Serialization.XmlElementAttribute("SessionAuth", GetType(DPAcctInqMtvnSvcReqSvcSecuritySessionAuth))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcSecurityBasicAuth
        
        Private usrIDField As String
        
        Private pwdField As String
        
        '''<remarks/>
        Public Property UsrID() As String
            Get
                Return Me.usrIDField
            End Get
            Set
                Me.usrIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pwd() As String
            Get
                Return Me.pwdField
            End Get
            Set
                Me.pwdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcSecuritySAMLAuth
        
        Private assertionField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Assertion")>  _
        Public Property Assertion() As String()
            Get
                Return Me.assertionField
            End Get
            Set
                Me.assertionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcSecuritySessionAuth
        
        Private itemField As String
        
        Private itemElementNameField As ItemChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("HttpSessionID", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("SessionID", GetType(String)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="mtvnCWDPAcctInqSvcReq", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        HttpSessionID
        
        '''<remarks/>
        SessionID
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcReq")>  _
    Partial Public Class DPAcctInqMtvnSvcReqSvcMsgData
        
        Private dPAcctInqReqDataField As DPAcctInqReqData
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="mtvnCWDPAcctInqReqData")>  _
        Public Property DPAcctInqReqData() As DPAcctInqReqData
            Get
                Return Me.dPAcctInqReqDataField
            End Get
            Set
                Me.dPAcctInqReqDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqReqData")>  _
    Partial Public Class DPAcctInqReqData
        
        Private e20007Field As String
        
        Private e301510Field As String
        
        Private e300344Field As String
        
        Private e20665Field As String
        
        Private e310045Field As String
        
        Private e21092Field As String
        
        Private e21093Field As String
        
        '''<remarks/>
        Public Property E20007() As String
            Get
                Return Me.e20007Field
            End Get
            Set
                Me.e20007Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E301510() As String
            Get
                Return Me.e301510Field
            End Get
            Set
                Me.e301510Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E300344() As String
            Get
                Return Me.e300344Field
            End Get
            Set
                Me.e300344Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20665() As String
            Get
                Return Me.e20665Field
            End Get
            Set
                Me.e20665Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E310045() As String
            Get
                Return Me.e310045Field
            End Get
            Set
                Me.e310045Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21092() As String
            Get
                Return Me.e21092Field
            End Get
            Set
                Me.e21092Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21093() As String
            Get
                Return Me.e21093Field
            End Get
            Set
                Me.e21093Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Partial Public Class DPAcctInqMtvnSvcRes
        
        Private mtvnSvcVerField As DPAcctInqMtvnSvcResMtvnSvcVer
        
        Private msgUUIDField As String
        
        Private svcField() As DPAcctInqMtvnSvcResSvc
        
        Private errCdeField As String
        
        Private errMsgField As String
        
        '''<remarks/>
        Public Property MtvnSvcVer() As DPAcctInqMtvnSvcResMtvnSvcVer
            Get
                Return Me.mtvnSvcVerField
            End Get
            Set
                Me.mtvnSvcVerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MsgUUID() As String
            Get
                Return Me.msgUUIDField
            End Get
            Set
                Me.msgUUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Svc")>  _
        Public Property Svc() As DPAcctInqMtvnSvcResSvc()
            Get
                Return Me.svcField
            End Get
            Set
                Me.svcField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrCde() As String
            Get
                Return Me.errCdeField
            End Get
            Set
                Me.errCdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrMsg() As String
            Get
                Return Me.errMsgField
            End Get
            Set
                Me.errMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Public Enum DPAcctInqMtvnSvcResMtvnSvcVer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1.0")>  _
        Item10
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Partial Public Class DPAcctInqMtvnSvcResSvc
        
        Private svcParmsField As DPAcctInqMtvnSvcResSvcSvcParms
        
        Private msgDataField As DPAcctInqMtvnSvcResSvcMsgData
        
        Private errCdeField As String
        
        Private errMsgField As String
        
        '''<remarks/>
        Public Property SvcParms() As DPAcctInqMtvnSvcResSvcSvcParms
            Get
                Return Me.svcParmsField
            End Get
            Set
                Me.svcParmsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MsgData() As DPAcctInqMtvnSvcResSvcMsgData
            Get
                Return Me.msgDataField
            End Get
            Set
                Me.msgDataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrCde() As String
            Get
                Return Me.errCdeField
            End Get
            Set
                Me.errCdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrMsg() As String
            Get
                Return Me.errMsgField
            End Get
            Set
                Me.errMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Partial Public Class DPAcctInqMtvnSvcResSvcSvcParms
        
        Private applIDField As DPAcctInqMtvnSvcResSvcSvcParmsApplID
        
        Private svcIDField As DPAcctInqMtvnSvcResSvcSvcParmsSvcID
        
        Private svcVerField As DPAcctInqMtvnSvcResSvcSvcParmsSvcVer
        
        Private rqstUUIDField As String
        
        '''<remarks/>
        Public Property ApplID() As DPAcctInqMtvnSvcResSvcSvcParmsApplID
            Get
                Return Me.applIDField
            End Get
            Set
                Me.applIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SvcID() As DPAcctInqMtvnSvcResSvcSvcParmsSvcID
            Get
                Return Me.svcIDField
            End Get
            Set
                Me.svcIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SvcVer() As DPAcctInqMtvnSvcResSvcSvcParmsSvcVer
            Get
                Return Me.svcVerField
            End Get
            Set
                Me.svcVerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RqstUUID() As String
            Get
                Return Me.rqstUUIDField
            End Get
            Set
                Me.rqstUUIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Public Enum DPAcctInqMtvnSvcResSvcSvcParmsApplID
        
        '''<remarks/>
        DP
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Public Enum DPAcctInqMtvnSvcResSvcSvcParmsSvcID
        
        '''<remarks/>
        DPAcctInq
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Public Enum DPAcctInqMtvnSvcResSvcSvcParmsSvcVer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("8.0")>  _
        Item80
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqSvcRes")>  _
    Partial Public Class DPAcctInqMtvnSvcResSvcMsgData
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DPAcctInqResData", GetType(DPAcctInqResData), [Namespace]:="mtvnCWDPAcctInqResData"),  _
         System.Xml.Serialization.XmlElementAttribute("DefaultResData", GetType(String))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqResData")>  _
    Partial Public Class DPAcctInqResData
        
        Private e20007Field As String
        
        Private e301510Field As String
        
        Private e300344Field As String
        
        Private e20665Field As String
        
        Private e310045Field As String
        
        Private e21092Field As String
        
        Private e21093Field As String
        
        Private e21634Field As String
        
        Private e21613Field As String
        
        Private e20142Field As String
        
        Private e21604Field As String
        
        Private e21638Field As String
        
        Private e20279Field As String
        
        Private e20278Field As String
        
        Private e20071Field As String
        
        Private e20297Field As String
        
        Private e20298Field As String
        
        Private e20299Field As String
        
        Private e20325Field As String
        
        Private e20326Field As String
        
        Private e20327Field As String
        
        Private e20328Field As String
        
        Private e20329Field As String
        
        Private e20330Field As String
        
        Private e21623Field As String
        
        Private e21642Field As String
        
        Private e20149Field As String
        
        Private e20146Field As String
        
        Private e20052Field As String
        
        Private e21632Field As String
        
        Private e21667Field As String
        
        Private e20418Field As String
        
        Private e21661Field As String
        
        Private e20923Field As String
        
        Private e21631Field As String
        
        Private e20590Field As String
        
        Private e20336Field As String
        
        Private e20445Field As String
        
        Private e20448Field As String
        
        Private e310046Field As String
        
        Private e20335Field As String
        
        Private e310047Field As String
        
        Private e20677Field As String
        
        Private e20671Field As String
        
        Private e20696Field As String
        
        Private e20678Field As String
        
        Private e20699Field As String
        
        Private e20713Field As String
        
        Private e20417Field As String
        
        Private e20156Field As String
        
        Private e20049Field As String
        
        Private e20050Field As String
        
        Private e21657Field As String
        
        Private e20065Field As String
        
        Private e20102Field As String
        
        Private e20117Field As String
        
        Private e20913Field As String
        
        Private e20914Field As String
        
        Private e21669Field As String
        
        Private e21670Field As String
        
        Private e21671Field As String
        
        Private e21672Field As String
        
        Private e22755Field As String
        
        Private e22758Field As String
        
        Private e20789Field As String
        
        Private e20790Field As String
        
        Private e20791Field As String
        
        Private e20792Field As String
        
        Private e20793Field As String
        
        Private e20794Field As String
        
        Private e20795Field As String
        
        Private e20796Field As String
        
        Private e20797Field As String
        
        Private e20798Field As String
        
        Private e20799Field As String
        
        Private e20800Field As String
        
        Private e20802Field As String
        
        Private e20803Field As String
        
        Private e20804Field As String
        
        Private e20805Field As String
        
        Private e20806Field As String
        
        Private e20807Field As String
        
        Private e20808Field As String
        
        Private e20809Field As String
        
        Private e20810Field As String
        
        Private e20811Field As String
        
        Private e20812Field As String
        
        Private e20813Field As String
        
        Private e20814Field As String
        
        Private e22880Field As String
        
        Private e20632Field As String
        
        Private e22770Field As String
        
        Private e23037Field As String
        
        Private e23038Field As String
        
        Private e23039Field As String
        
        Private e21287Field As String
        
        Private e21288Field As String
        
        Private e21289Field As String
        
        Private e21040Field As String
        
        Private e22974Field As String
        
        Private e22975Field As String
        
        Private e22977Field As String
        
        Private e20046Field As String
        
        Private e20108Field As String
        
        Private e20057Field As String
        
        Private e20261Field As String
        
        Private e20110Field As String
        
        Private errCdeField As String
        
        Private errResnCdeField As String
        
        Private applMsgLstField() As DPAcctInqResDataApplMsg
        
        '''<remarks/>
        Public Property E20007() As String
            Get
                Return Me.e20007Field
            End Get
            Set
                Me.e20007Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E301510() As String
            Get
                Return Me.e301510Field
            End Get
            Set
                Me.e301510Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E300344() As String
            Get
                Return Me.e300344Field
            End Get
            Set
                Me.e300344Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20665() As String
            Get
                Return Me.e20665Field
            End Get
            Set
                Me.e20665Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E310045() As String
            Get
                Return Me.e310045Field
            End Get
            Set
                Me.e310045Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21092() As String
            Get
                Return Me.e21092Field
            End Get
            Set
                Me.e21092Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21093() As String
            Get
                Return Me.e21093Field
            End Get
            Set
                Me.e21093Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21634() As String
            Get
                Return Me.e21634Field
            End Get
            Set
                Me.e21634Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21613() As String
            Get
                Return Me.e21613Field
            End Get
            Set
                Me.e21613Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20142() As String
            Get
                Return Me.e20142Field
            End Get
            Set
                Me.e20142Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21604() As String
            Get
                Return Me.e21604Field
            End Get
            Set
                Me.e21604Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21638() As String
            Get
                Return Me.e21638Field
            End Get
            Set
                Me.e21638Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20279() As String
            Get
                Return Me.e20279Field
            End Get
            Set
                Me.e20279Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20278() As String
            Get
                Return Me.e20278Field
            End Get
            Set
                Me.e20278Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20071() As String
            Get
                Return Me.e20071Field
            End Get
            Set
                Me.e20071Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20297() As String
            Get
                Return Me.e20297Field
            End Get
            Set
                Me.e20297Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20298() As String
            Get
                Return Me.e20298Field
            End Get
            Set
                Me.e20298Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20299() As String
            Get
                Return Me.e20299Field
            End Get
            Set
                Me.e20299Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20325() As String
            Get
                Return Me.e20325Field
            End Get
            Set
                Me.e20325Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20326() As String
            Get
                Return Me.e20326Field
            End Get
            Set
                Me.e20326Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20327() As String
            Get
                Return Me.e20327Field
            End Get
            Set
                Me.e20327Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20328() As String
            Get
                Return Me.e20328Field
            End Get
            Set
                Me.e20328Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20329() As String
            Get
                Return Me.e20329Field
            End Get
            Set
                Me.e20329Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20330() As String
            Get
                Return Me.e20330Field
            End Get
            Set
                Me.e20330Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21623() As String
            Get
                Return Me.e21623Field
            End Get
            Set
                Me.e21623Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21642() As String
            Get
                Return Me.e21642Field
            End Get
            Set
                Me.e21642Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20149() As String
            Get
                Return Me.e20149Field
            End Get
            Set
                Me.e20149Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20146() As String
            Get
                Return Me.e20146Field
            End Get
            Set
                Me.e20146Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20052() As String
            Get
                Return Me.e20052Field
            End Get
            Set
                Me.e20052Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21632() As String
            Get
                Return Me.e21632Field
            End Get
            Set
                Me.e21632Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21667() As String
            Get
                Return Me.e21667Field
            End Get
            Set
                Me.e21667Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20418() As String
            Get
                Return Me.e20418Field
            End Get
            Set
                Me.e20418Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21661() As String
            Get
                Return Me.e21661Field
            End Get
            Set
                Me.e21661Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20923() As String
            Get
                Return Me.e20923Field
            End Get
            Set
                Me.e20923Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21631() As String
            Get
                Return Me.e21631Field
            End Get
            Set
                Me.e21631Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20590() As String
            Get
                Return Me.e20590Field
            End Get
            Set
                Me.e20590Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20336() As String
            Get
                Return Me.e20336Field
            End Get
            Set
                Me.e20336Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20445() As String
            Get
                Return Me.e20445Field
            End Get
            Set
                Me.e20445Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20448() As String
            Get
                Return Me.e20448Field
            End Get
            Set
                Me.e20448Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E310046() As String
            Get
                Return Me.e310046Field
            End Get
            Set
                Me.e310046Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20335() As String
            Get
                Return Me.e20335Field
            End Get
            Set
                Me.e20335Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E310047() As String
            Get
                Return Me.e310047Field
            End Get
            Set
                Me.e310047Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20677() As String
            Get
                Return Me.e20677Field
            End Get
            Set
                Me.e20677Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20671() As String
            Get
                Return Me.e20671Field
            End Get
            Set
                Me.e20671Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20696() As String
            Get
                Return Me.e20696Field
            End Get
            Set
                Me.e20696Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20678() As String
            Get
                Return Me.e20678Field
            End Get
            Set
                Me.e20678Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20699() As String
            Get
                Return Me.e20699Field
            End Get
            Set
                Me.e20699Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20713() As String
            Get
                Return Me.e20713Field
            End Get
            Set
                Me.e20713Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20417() As String
            Get
                Return Me.e20417Field
            End Get
            Set
                Me.e20417Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20156() As String
            Get
                Return Me.e20156Field
            End Get
            Set
                Me.e20156Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20049() As String
            Get
                Return Me.e20049Field
            End Get
            Set
                Me.e20049Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20050() As String
            Get
                Return Me.e20050Field
            End Get
            Set
                Me.e20050Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21657() As String
            Get
                Return Me.e21657Field
            End Get
            Set
                Me.e21657Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20065() As String
            Get
                Return Me.e20065Field
            End Get
            Set
                Me.e20065Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20102() As String
            Get
                Return Me.e20102Field
            End Get
            Set
                Me.e20102Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20117() As String
            Get
                Return Me.e20117Field
            End Get
            Set
                Me.e20117Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20913() As String
            Get
                Return Me.e20913Field
            End Get
            Set
                Me.e20913Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20914() As String
            Get
                Return Me.e20914Field
            End Get
            Set
                Me.e20914Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21669() As String
            Get
                Return Me.e21669Field
            End Get
            Set
                Me.e21669Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21670() As String
            Get
                Return Me.e21670Field
            End Get
            Set
                Me.e21670Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21671() As String
            Get
                Return Me.e21671Field
            End Get
            Set
                Me.e21671Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21672() As String
            Get
                Return Me.e21672Field
            End Get
            Set
                Me.e21672Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E22755() As String
            Get
                Return Me.e22755Field
            End Get
            Set
                Me.e22755Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E22758() As String
            Get
                Return Me.e22758Field
            End Get
            Set
                Me.e22758Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20789() As String
            Get
                Return Me.e20789Field
            End Get
            Set
                Me.e20789Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20790() As String
            Get
                Return Me.e20790Field
            End Get
            Set
                Me.e20790Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20791() As String
            Get
                Return Me.e20791Field
            End Get
            Set
                Me.e20791Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20792() As String
            Get
                Return Me.e20792Field
            End Get
            Set
                Me.e20792Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20793() As String
            Get
                Return Me.e20793Field
            End Get
            Set
                Me.e20793Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20794() As String
            Get
                Return Me.e20794Field
            End Get
            Set
                Me.e20794Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20795() As String
            Get
                Return Me.e20795Field
            End Get
            Set
                Me.e20795Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20796() As String
            Get
                Return Me.e20796Field
            End Get
            Set
                Me.e20796Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20797() As String
            Get
                Return Me.e20797Field
            End Get
            Set
                Me.e20797Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20798() As String
            Get
                Return Me.e20798Field
            End Get
            Set
                Me.e20798Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20799() As String
            Get
                Return Me.e20799Field
            End Get
            Set
                Me.e20799Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20800() As String
            Get
                Return Me.e20800Field
            End Get
            Set
                Me.e20800Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20802() As String
            Get
                Return Me.e20802Field
            End Get
            Set
                Me.e20802Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20803() As String
            Get
                Return Me.e20803Field
            End Get
            Set
                Me.e20803Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20804() As String
            Get
                Return Me.e20804Field
            End Get
            Set
                Me.e20804Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20805() As String
            Get
                Return Me.e20805Field
            End Get
            Set
                Me.e20805Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20806() As String
            Get
                Return Me.e20806Field
            End Get
            Set
                Me.e20806Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20807() As String
            Get
                Return Me.e20807Field
            End Get
            Set
                Me.e20807Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20808() As String
            Get
                Return Me.e20808Field
            End Get
            Set
                Me.e20808Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20809() As String
            Get
                Return Me.e20809Field
            End Get
            Set
                Me.e20809Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20810() As String
            Get
                Return Me.e20810Field
            End Get
            Set
                Me.e20810Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20811() As String
            Get
                Return Me.e20811Field
            End Get
            Set
                Me.e20811Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20812() As String
            Get
                Return Me.e20812Field
            End Get
            Set
                Me.e20812Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20813() As String
            Get
                Return Me.e20813Field
            End Get
            Set
                Me.e20813Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20814() As String
            Get
                Return Me.e20814Field
            End Get
            Set
                Me.e20814Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E22880() As String
            Get
                Return Me.e22880Field
            End Get
            Set
                Me.e22880Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20632() As String
            Get
                Return Me.e20632Field
            End Get
            Set
                Me.e20632Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E22770() As String
            Get
                Return Me.e22770Field
            End Get
            Set
                Me.e22770Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E23037() As String
            Get
                Return Me.e23037Field
            End Get
            Set
                Me.e23037Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E23038() As String
            Get
                Return Me.e23038Field
            End Get
            Set
                Me.e23038Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E23039() As String
            Get
                Return Me.e23039Field
            End Get
            Set
                Me.e23039Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21287() As String
            Get
                Return Me.e21287Field
            End Get
            Set
                Me.e21287Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21288() As String
            Get
                Return Me.e21288Field
            End Get
            Set
                Me.e21288Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21289() As String
            Get
                Return Me.e21289Field
            End Get
            Set
                Me.e21289Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E21040() As String
            Get
                Return Me.e21040Field
            End Get
            Set
                Me.e21040Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E22974() As String
            Get
                Return Me.e22974Field
            End Get
            Set
                Me.e22974Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E22975() As String
            Get
                Return Me.e22975Field
            End Get
            Set
                Me.e22975Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E22977() As String
            Get
                Return Me.e22977Field
            End Get
            Set
                Me.e22977Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20046() As String
            Get
                Return Me.e20046Field
            End Get
            Set
                Me.e20046Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20108() As String
            Get
                Return Me.e20108Field
            End Get
            Set
                Me.e20108Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20057() As String
            Get
                Return Me.e20057Field
            End Get
            Set
                Me.e20057Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20261() As String
            Get
                Return Me.e20261Field
            End Get
            Set
                Me.e20261Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property E20110() As String
            Get
                Return Me.e20110Field
            End Get
            Set
                Me.e20110Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrCde() As String
            Get
                Return Me.errCdeField
            End Get
            Set
                Me.errCdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrResnCde() As String
            Get
                Return Me.errResnCdeField
            End Get
            Set
                Me.errResnCdeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ApplMsg", IsNullable:=false)>  _
        Public Property ApplMsgLst() As DPAcctInqResDataApplMsg()
            Get
                Return Me.applMsgLstField
            End Get
            Set
                Me.applMsgLstField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5476"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="mtvnCWDPAcctInqResData")>  _
    Partial Public Class DPAcctInqResDataApplMsg
        
        Private applMsgApplIdField As String
        
        Private applMsgNbrField As String
        
        Private applMsgTxtField As String
        
        Private applMsgErrIndField As String
        
        Private applMsgFldField As String
        
        '''<remarks/>
        Public Property ApplMsgApplId() As String
            Get
                Return Me.applMsgApplIdField
            End Get
            Set
                Me.applMsgApplIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplMsgNbr() As String
            Get
                Return Me.applMsgNbrField
            End Get
            Set
                Me.applMsgNbrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplMsgTxt() As String
            Get
                Return Me.applMsgTxtField
            End Get
            Set
                Me.applMsgTxtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplMsgErrInd() As String
            Get
                Return Me.applMsgErrIndField
            End Get
            Set
                Me.applMsgErrIndField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplMsgFld() As String
            Get
                Return Me.applMsgFldField
            End Get
            Set
                Me.applMsgFldField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub DPAcctInqCompletedEventHandler(ByVal sender As Object, ByVal e As DPAcctInqCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DPAcctInqCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DPAcctInqMtvnSvcRes
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DPAcctInqMtvnSvcRes)
            End Get
        End Property
    End Class
End Namespace
