'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace EPL.UserAuthentication

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UserAuthenticationServiceBinding", [Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/")>  _
    Partial Public Class UserAuthenticationService
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol

        Private PerformSignOnOperationCompleted As System.Threading.SendOrPostCallback

        Private PerformSignOffOperationCompleted As System.Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.LoansPQWSWrappers_EPL_UserAuthentication_UserAuthenticationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property

        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property

        '''<remarks/>
        Public Event PerformSignOnCompleted As PerformSignOnCompletedEventHandler

        '''<remarks/>
        Public Event PerformSignOffCompleted As PerformSignOffCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function PerformSignOn(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")> ByVal SignOnReq As SignOnReq) As <System.Xml.Serialization.XmlElementAttribute("SignOnResp", [Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")> SignOnResp
            Dim results() As Object = Me.Invoke("PerformSignOn", New Object() {SignOnReq})
            Return CType(results(0),SignOnResp)
        End Function

        '''<remarks/>
        Public Function BeginPerformSignOn(ByVal SignOnReq As SignOnReq, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PerformSignOn", New Object() {SignOnReq}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndPerformSignOn(ByVal asyncResult As System.IAsyncResult) As SignOnResp
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SignOnResp)
        End Function

        '''<remarks/>
        Public Overloads Sub PerformSignOnAsync(ByVal SignOnReq As SignOnReq)
            Me.PerformSignOnAsync(SignOnReq, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub PerformSignOnAsync(ByVal SignOnReq As SignOnReq, ByVal userState As Object)
            If (Me.PerformSignOnOperationCompleted Is Nothing) Then
                Me.PerformSignOnOperationCompleted = AddressOf Me.OnPerformSignOnOperationCompleted
            End If
            Me.InvokeAsync("PerformSignOn", New Object() {SignOnReq}, Me.PerformSignOnOperationCompleted, userState)
        End Sub

        Private Sub OnPerformSignOnOperationCompleted(ByVal arg As Object)
            If (Not (Me.PerformSignOnCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PerformSignOnCompleted(Me, New PerformSignOnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function PerformSignOff(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")> ByVal SignOffReq As SignOffReq) As <System.Xml.Serialization.XmlElementAttribute("SignOffResp", [Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")> SignOffResp
            Dim results() As Object = Me.Invoke("PerformSignOff", New Object() {SignOffReq})
            Return CType(results(0),SignOffResp)
        End Function

        '''<remarks/>
        Public Function BeginPerformSignOff(ByVal SignOffReq As SignOffReq, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PerformSignOff", New Object() {SignOffReq}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndPerformSignOff(ByVal asyncResult As System.IAsyncResult) As SignOffResp
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SignOffResp)
        End Function

        '''<remarks/>
        Public Overloads Sub PerformSignOffAsync(ByVal SignOffReq As SignOffReq)
            Me.PerformSignOffAsync(SignOffReq, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub PerformSignOffAsync(ByVal SignOffReq As SignOffReq, ByVal userState As Object)
            If (Me.PerformSignOffOperationCompleted Is Nothing) Then
                Me.PerformSignOffOperationCompleted = AddressOf Me.OnPerformSignOffOperationCompleted
            End If
            Me.InvokeAsync("PerformSignOff", New Object() {SignOffReq}, Me.PerformSignOffOperationCompleted, userState)
        End Sub

        Private Sub OnPerformSignOffOperationCompleted(ByVal arg As Object)
            If (Not (Me.PerformSignOffCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PerformSignOffCompleted(Me, New PerformSignOffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class SignOnReq

        Private msgReqHeaderField As MsgReqHeader

        Private userCredentialsField As UserCredentials

        Private drawerNumField As Long

        Private terminalIPAddressField As String

        '''<remarks/>
        Public Property msgReqHeader() As MsgReqHeader
            Get
                Return Me.msgReqHeaderField
            End Get
            Set
                Me.msgReqHeaderField = value
            End Set
        End Property

        '''<remarks/>
        Public Property userCredentials() As UserCredentials
            Get
                Return Me.userCredentialsField
            End Get
            Set
                Me.userCredentialsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property drawerNum() As Long
            Get
                Return Me.drawerNumField
            End Get
            Set
                Me.drawerNumField = value
            End Set
        End Property

        '''<remarks/>
        Public Property terminalIPAddress() As String
            Get
                Return Me.terminalIPAddressField
            End Get
            Set
                Me.terminalIPAddressField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class MsgReqHeader

        Private serviceRequesterUIDField As String

        Private serviceProviderUIDField As String

        Private sessionTokenField As String

        Private overridingUserField As UserCredentials

        '''<remarks/>
        Public Property serviceRequesterUID() As String
            Get
                Return Me.serviceRequesterUIDField
            End Get
            Set
                Me.serviceRequesterUIDField = value
            End Set
        End Property

        '''<remarks/>
        Public Property serviceProviderUID() As String
            Get
                Return Me.serviceProviderUIDField
            End Get
            Set
                Me.serviceProviderUIDField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property sessionToken() As String
            Get
                Return Me.sessionTokenField
            End Get
            Set
                Me.sessionTokenField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property overridingUser() As UserCredentials
            Get
                Return Me.overridingUserField
            End Get
            Set
                Me.overridingUserField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class UserCredentials

        Private userIdField As String

        Private userPasswordField As String

        '''<remarks/>
        Public Property userId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property

        '''<remarks/>
        Public Property userPassword() As String
            Get
                Return Me.userPasswordField
            End Get
            Set
                Me.userPasswordField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class SignOffResp

        Private msgRespHeaderField As MsgRespHeader

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property msgRespHeader() As MsgRespHeader
            Get
                Return Me.msgRespHeaderField
            End Get
            Set
                Me.msgRespHeaderField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class MsgRespHeader

        Private errorsField() As ErrorType

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("errorType", IsNullable:=false)>  _
        Public Property errors() As ErrorType()
            Get
                Return Me.errorsField
            End Get
            Set
                Me.errorsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class ErrorType

        Private errorCodeField As String

        Private errorDescriptionField As String

        Private errorSourceField As String

        Private overrideAllowedField As Boolean

        Private overrideLevelNeededField As Integer

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property errorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property errorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property errorSource() As String
            Get
                Return Me.errorSourceField
            End Get
            Set
                Me.errorSourceField = value
            End Set
        End Property

        '''<remarks/>
        Public Property overrideAllowed() As Boolean
            Get
                Return Me.overrideAllowedField
            End Get
            Set
                Me.overrideAllowedField = value
            End Set
        End Property

        '''<remarks/>
        Public Property overrideLevelNeeded() As Integer
            Get
                Return Me.overrideLevelNeededField
            End Get
            Set
                Me.overrideLevelNeededField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class SignOffReq

        Private msgReqHeaderField As MsgReqHeader

        '''<remarks/>
        Public Property msgReqHeader() As MsgReqHeader
            Get
                Return Me.msgReqHeaderField
            End Get
            Set
                Me.msgReqHeaderField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.eplinc.com/services/UserAuthenticationService/2006-05-01/schema")>  _
    Partial Public Class SignOnResp

        Private msgRespHeaderField As MsgRespHeader

        Private sessionTokenField As String

        '''<remarks/>
        Public Property msgRespHeader() As MsgRespHeader
            Get
                Return Me.msgRespHeaderField
            End Get
            Set
                Me.msgRespHeaderField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property sessionToken() As String
            Get
                Return Me.sessionTokenField
            End Get
            Set
                Me.sessionTokenField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub PerformSignOnCompletedEventHandler(ByVal sender As Object, ByVal e As PerformSignOnCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PerformSignOnCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As SignOnResp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SignOnResp)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub PerformSignOffCompletedEventHandler(ByVal sender As Object, ByVal e As PerformSignOffCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PerformSignOffCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As SignOffResp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SignOffResp)
            End Get
        End Property
    End Class
End Namespace
