'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
'
Namespace EFundsKbaService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="efundskbaSoapBinding", [Namespace]:="urn:efundskba")>  _
    Partial Public Class KbaServiceServiceWse
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        
        Private kbaQuestionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaAnswerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaAuthenticateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaQuestionV002OperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaAnswerV002OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.LoansPQWSWrappers_EFundsKbaService_KbaServiceService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event kbaQuestionCompleted As kbaQuestionCompletedEventHandler
        
        '''<remarks/>
        Public Event kbaAnswerCompleted As kbaAnswerCompletedEventHandler
        
        '''<remarks/>
        Public Event kbaAuthenticateCompleted As kbaAuthenticateCompletedEventHandler
        
        '''<remarks/>
        Public Event kbaQuestionV002Completed As kbaQuestionV002CompletedEventHandler
        
        '''<remarks/>
        Public Event kbaAnswerV002Completed As kbaAnswerV002CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaQuestion(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson) As <System.Xml.Serialization.SoapElementAttribute("kbaQuestionReturn")> KBAQuestions
            Dim results() As Object = Me.Invoke("kbaQuestion", New Object() {in0, in1, in2})
            Return CType(results(0),KBAQuestions)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionAsync(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson)
            Me.kbaQuestionAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionAsync(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson, ByVal userState As Object)
            If (Me.kbaQuestionOperationCompleted Is Nothing) Then
                Me.kbaQuestionOperationCompleted = AddressOf Me.OnkbaQuestionOperationCompleted
            End If
            Me.InvokeAsync("kbaQuestion", New Object() {in0, in1, in2}, Me.kbaQuestionOperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaQuestionOperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaQuestionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaQuestionCompleted(Me, New kbaQuestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaAnswer(ByVal in0 As String, ByVal in1 As KBAAnswers) As <System.Xml.Serialization.SoapElementAttribute("kbaAnswerReturn")> KBADecision
            Dim results() As Object = Me.Invoke("kbaAnswer", New Object() {in0, in1})
            Return CType(results(0),KBADecision)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerAsync(ByVal in0 As String, ByVal in1 As KBAAnswers)
            Me.kbaAnswerAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerAsync(ByVal in0 As String, ByVal in1 As KBAAnswers, ByVal userState As Object)
            If (Me.kbaAnswerOperationCompleted Is Nothing) Then
                Me.kbaAnswerOperationCompleted = AddressOf Me.OnkbaAnswerOperationCompleted
            End If
            Me.InvokeAsync("kbaAnswer", New Object() {in0, in1}, Me.kbaAnswerOperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaAnswerOperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaAnswerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaAnswerCompleted(Me, New kbaAnswerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaAuthenticate(ByVal in0 As String, ByVal in1 As String) As <System.Xml.Serialization.SoapElementAttribute("kbaAuthenticateReturn")> String
            Dim results() As Object = Me.Invoke("kbaAuthenticate", New Object() {in0, in1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaAuthenticateAsync(ByVal in0 As String, ByVal in1 As String)
            Me.kbaAuthenticateAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaAuthenticateAsync(ByVal in0 As String, ByVal in1 As String, ByVal userState As Object)
            If (Me.kbaAuthenticateOperationCompleted Is Nothing) Then
                Me.kbaAuthenticateOperationCompleted = AddressOf Me.OnkbaAuthenticateOperationCompleted
            End If
            Me.InvokeAsync("kbaAuthenticate", New Object() {in0, in1}, Me.kbaAuthenticateOperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaAuthenticateOperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaAuthenticateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaAuthenticateCompleted(Me, New kbaAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaQuestionV002(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson1) As <System.Xml.Serialization.SoapElementAttribute("kbaQuestionV002Return")> KBAQuestions
            Dim results() As Object = Me.Invoke("kbaQuestionV002", New Object() {in0, in1, in2})
            Return CType(results(0),KBAQuestions)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionV002Async(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson1)
            Me.kbaQuestionV002Async(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionV002Async(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson1, ByVal userState As Object)
            If (Me.kbaQuestionV002OperationCompleted Is Nothing) Then
                Me.kbaQuestionV002OperationCompleted = AddressOf Me.OnkbaQuestionV002OperationCompleted
            End If
            Me.InvokeAsync("kbaQuestionV002", New Object() {in0, in1, in2}, Me.kbaQuestionV002OperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaQuestionV002OperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaQuestionV002CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaQuestionV002Completed(Me, New kbaQuestionV002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaAnswerV002(ByVal in0 As String, ByVal in1 As KBAAnswers) As <System.Xml.Serialization.SoapElementAttribute("kbaAnswerV002Return")> KBADecision1
            Dim results() As Object = Me.Invoke("kbaAnswerV002", New Object() {in0, in1})
            Return CType(results(0),KBADecision1)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerV002Async(ByVal in0 As String, ByVal in1 As KBAAnswers)
            Me.kbaAnswerV002Async(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerV002Async(ByVal in0 As String, ByVal in1 As KBAAnswers, ByVal userState As Object)
            If (Me.kbaAnswerV002OperationCompleted Is Nothing) Then
                Me.kbaAnswerV002OperationCompleted = AddressOf Me.OnkbaAnswerV002OperationCompleted
            End If
            Me.InvokeAsync("kbaAnswerV002", New Object() {in0, in1}, Me.kbaAnswerV002OperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaAnswerV002OperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaAnswerV002CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaAnswerV002Completed(Me, New kbaAnswerV002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="efundskbaSoapBinding", [Namespace]:="urn:efundskba")>  _
    Partial Public Class KbaServiceService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private kbaQuestionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaAnswerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaAuthenticateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaQuestionV002OperationCompleted As System.Threading.SendOrPostCallback
        
        Private kbaAnswerV002OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.LoansPQWSWrappers_EFundsKbaService_KbaServiceService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event kbaQuestionCompleted As kbaQuestionCompletedEventHandler
        
        '''<remarks/>
        Public Event kbaAnswerCompleted As kbaAnswerCompletedEventHandler
        
        '''<remarks/>
        Public Event kbaAuthenticateCompleted As kbaAuthenticateCompletedEventHandler
        
        '''<remarks/>
        Public Event kbaQuestionV002Completed As kbaQuestionV002CompletedEventHandler
        
        '''<remarks/>
        Public Event kbaAnswerV002Completed As kbaAnswerV002CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaQuestion(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson) As <System.Xml.Serialization.SoapElementAttribute("kbaQuestionReturn")> KBAQuestions
            Dim results() As Object = Me.Invoke("kbaQuestion", New Object() {in0, in1, in2})
            Return CType(results(0),KBAQuestions)
        End Function
        
        '''<remarks/>
        Public Function BeginkbaQuestion(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("kbaQuestion", New Object() {in0, in1, in2}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndkbaQuestion(ByVal asyncResult As System.IAsyncResult) As KBAQuestions
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),KBAQuestions)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionAsync(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson)
            Me.kbaQuestionAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionAsync(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson, ByVal userState As Object)
            If (Me.kbaQuestionOperationCompleted Is Nothing) Then
                Me.kbaQuestionOperationCompleted = AddressOf Me.OnkbaQuestionOperationCompleted
            End If
            Me.InvokeAsync("kbaQuestion", New Object() {in0, in1, in2}, Me.kbaQuestionOperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaQuestionOperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaQuestionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaQuestionCompleted(Me, New kbaQuestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaAnswer(ByVal in0 As String, ByVal in1 As KBAAnswers) As <System.Xml.Serialization.SoapElementAttribute("kbaAnswerReturn")> KBADecision
            Dim results() As Object = Me.Invoke("kbaAnswer", New Object() {in0, in1})
            Return CType(results(0),KBADecision)
        End Function
        
        '''<remarks/>
        Public Function BeginkbaAnswer(ByVal in0 As String, ByVal in1 As KBAAnswers, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("kbaAnswer", New Object() {in0, in1}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndkbaAnswer(ByVal asyncResult As System.IAsyncResult) As KBADecision
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),KBADecision)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerAsync(ByVal in0 As String, ByVal in1 As KBAAnswers)
            Me.kbaAnswerAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerAsync(ByVal in0 As String, ByVal in1 As KBAAnswers, ByVal userState As Object)
            If (Me.kbaAnswerOperationCompleted Is Nothing) Then
                Me.kbaAnswerOperationCompleted = AddressOf Me.OnkbaAnswerOperationCompleted
            End If
            Me.InvokeAsync("kbaAnswer", New Object() {in0, in1}, Me.kbaAnswerOperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaAnswerOperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaAnswerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaAnswerCompleted(Me, New kbaAnswerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaAuthenticate(ByVal in0 As String, ByVal in1 As String) As <System.Xml.Serialization.SoapElementAttribute("kbaAuthenticateReturn")> String
            Dim results() As Object = Me.Invoke("kbaAuthenticate", New Object() {in0, in1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginkbaAuthenticate(ByVal in0 As String, ByVal in1 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("kbaAuthenticate", New Object() {in0, in1}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndkbaAuthenticate(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaAuthenticateAsync(ByVal in0 As String, ByVal in1 As String)
            Me.kbaAuthenticateAsync(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaAuthenticateAsync(ByVal in0 As String, ByVal in1 As String, ByVal userState As Object)
            If (Me.kbaAuthenticateOperationCompleted Is Nothing) Then
                Me.kbaAuthenticateOperationCompleted = AddressOf Me.OnkbaAuthenticateOperationCompleted
            End If
            Me.InvokeAsync("kbaAuthenticate", New Object() {in0, in1}, Me.kbaAuthenticateOperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaAuthenticateOperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaAuthenticateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaAuthenticateCompleted(Me, New kbaAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaQuestionV002(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson1) As <System.Xml.Serialization.SoapElementAttribute("kbaQuestionV002Return")> KBAQuestions
            Dim results() As Object = Me.Invoke("kbaQuestionV002", New Object() {in0, in1, in2})
            Return CType(results(0),KBAQuestions)
        End Function
        
        '''<remarks/>
        Public Function BeginkbaQuestionV002(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson1, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("kbaQuestionV002", New Object() {in0, in1, in2}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndkbaQuestionV002(ByVal asyncResult As System.IAsyncResult) As KBAQuestions
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),KBAQuestions)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionV002Async(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson1)
            Me.kbaQuestionV002Async(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaQuestionV002Async(ByVal in0 As String, ByVal in1 As KBAIdentification, ByVal in2 As KBAPerson1, ByVal userState As Object)
            If (Me.kbaQuestionV002OperationCompleted Is Nothing) Then
                Me.kbaQuestionV002OperationCompleted = AddressOf Me.OnkbaQuestionV002OperationCompleted
            End If
            Me.InvokeAsync("kbaQuestionV002", New Object() {in0, in1, in2}, Me.kbaQuestionV002OperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaQuestionV002OperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaQuestionV002CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaQuestionV002Completed(Me, New kbaQuestionV002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:efundskba", ResponseNamespace:="urn:efundskba")>  _
        Public Function kbaAnswerV002(ByVal in0 As String, ByVal in1 As KBAAnswers) As <System.Xml.Serialization.SoapElementAttribute("kbaAnswerV002Return")> KBADecision1
            Dim results() As Object = Me.Invoke("kbaAnswerV002", New Object() {in0, in1})
            Return CType(results(0),KBADecision1)
        End Function
        
        '''<remarks/>
        Public Function BeginkbaAnswerV002(ByVal in0 As String, ByVal in1 As KBAAnswers, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("kbaAnswerV002", New Object() {in0, in1}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndkbaAnswerV002(ByVal asyncResult As System.IAsyncResult) As KBADecision1
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),KBADecision1)
        End Function
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerV002Async(ByVal in0 As String, ByVal in1 As KBAAnswers)
            Me.kbaAnswerV002Async(in0, in1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub kbaAnswerV002Async(ByVal in0 As String, ByVal in1 As KBAAnswers, ByVal userState As Object)
            If (Me.kbaAnswerV002OperationCompleted Is Nothing) Then
                Me.kbaAnswerV002OperationCompleted = AddressOf Me.OnkbaAnswerV002OperationCompleted
            End If
            Me.InvokeAsync("kbaAnswerV002", New Object() {in0, in1}, Me.kbaAnswerV002OperationCompleted, userState)
        End Sub
        
        Private Sub OnkbaAnswerV002OperationCompleted(ByVal arg As Object)
            If (Not (Me.kbaAnswerV002CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent kbaAnswerV002Completed(Me, New kbaAnswerV002CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://V001.queryobjects.soap.penleyinc.com")>  _
    Partial Public Class KBAIdentification
        
        Private acquireridField As String
        
        Private configkeyField As String
        
        Private customeridField As String
        
        Private locationidField As String
        
        Private productcdField As String
        
        Private productversionbrField As String
        
        Private stagingField As Boolean
        
        Private userdefinedtransactiontext1Field As String
        
        Private userdefinedtransactiontext2Field As String
        
        Private userdefinedtransactiontext3Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property acquirerid() As String
            Get
                Return Me.acquireridField
            End Get
            Set
                Me.acquireridField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property configkey() As String
            Get
                Return Me.configkeyField
            End Get
            Set
                Me.configkeyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property customerid() As String
            Get
                Return Me.customeridField
            End Get
            Set
                Me.customeridField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property locationid() As String
            Get
                Return Me.locationidField
            End Get
            Set
                Me.locationidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property productcd() As String
            Get
                Return Me.productcdField
            End Get
            Set
                Me.productcdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property productversionbr() As String
            Get
                Return Me.productversionbrField
            End Get
            Set
                Me.productversionbrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property staging() As Boolean
            Get
                Return Me.stagingField
            End Get
            Set
                Me.stagingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property userdefinedtransactiontext1() As String
            Get
                Return Me.userdefinedtransactiontext1Field
            End Get
            Set
                Me.userdefinedtransactiontext1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property userdefinedtransactiontext2() As String
            Get
                Return Me.userdefinedtransactiontext2Field
            End Get
            Set
                Me.userdefinedtransactiontext2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property userdefinedtransactiontext3() As String
            Get
                Return Me.userdefinedtransactiontext3Field
            End Get
            Set
                Me.userdefinedtransactiontext3Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute(TypeName:="KBADecision", [Namespace]:="http://V002.replyobjects.soap.penleyinc.com")>  _
    Partial Public Class KBADecision1
        
        Private baseField As Integer
        
        Private decisionField As String
        
        Private scoreField As Integer
        
        Private kbaoidField As Integer
        
        '''<remarks/>
        Public Property base() As Integer
            Get
                Return Me.baseField
            End Get
            Set
                Me.baseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property decision() As String
            Get
                Return Me.decisionField
            End Get
            Set
                Me.decisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property score() As Integer
            Get
                Return Me.scoreField
            End Get
            Set
                Me.scoreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property kbaoid() As Integer
            Get
                Return Me.kbaoidField
            End Get
            Set
                Me.kbaoidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute(TypeName:="KBAPerson", [Namespace]:="http://V002.queryobjects.soap.penleyinc.com")>  _
    Partial Public Class KBAPerson1
        
        Private idvoidField As Integer
        
        Private addressField As String
        
        Private cityField As String
        
        Private dobField As String
        
        Private firstnameField As String
        
        Private lastnameField As String
        
        Private ssnField As String
        
        Private stateField As String
        
        Private zipField As String
        
        '''<remarks/>
        Public Property idvoid() As Integer
            Get
                Return Me.idvoidField
            End Get
            Set
                Me.idvoidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property city() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property dob() As String
            Get
                Return Me.dobField
            End Get
            Set
                Me.dobField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set
                Me.firstnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set
                Me.lastnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property ssn() As String
            Get
                Return Me.ssnField
            End Get
            Set
                Me.ssnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property state() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property zip() As String
            Get
                Return Me.zipField
            End Get
            Set
                Me.zipField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://V001.replyobjects.soap.penleyinc.com")>  _
    Partial Public Class KBADecision
        
        Private baseField As Integer
        
        Private decisionField As String
        
        Private scoreField As Integer
        
        '''<remarks/>
        Public Property base() As Integer
            Get
                Return Me.baseField
            End Get
            Set
                Me.baseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property decision() As String
            Get
                Return Me.decisionField
            End Get
            Set
                Me.decisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property score() As Integer
            Get
                Return Me.scoreField
            End Get
            Set
                Me.scoreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://V001.queryobjects.soap.penleyinc.com")>  _
    Partial Public Class KBAAnswers
        
        Private answer1QuestionIdField As String
        
        Private answer1ResponseIdField As String
        
        Private answer2QuestionIdField As String
        
        Private answer2ResponseIdField As String
        
        Private answer3QuestionIdField As String
        
        Private answer3ResponseIdField As String
        
        Private answer4QuestionIdField As String
        
        Private answer4ResponseIdField As String
        
        Private answer5QuestionIdField As String
        
        Private answer5ResponseIdField As String
        
        Private answer6QuestionIdField As String
        
        Private answer6ResponseIdField As String
        
        Private quizidField As String
        
        Private transidField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer1QuestionId() As String
            Get
                Return Me.answer1QuestionIdField
            End Get
            Set
                Me.answer1QuestionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer1ResponseId() As String
            Get
                Return Me.answer1ResponseIdField
            End Get
            Set
                Me.answer1ResponseIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer2QuestionId() As String
            Get
                Return Me.answer2QuestionIdField
            End Get
            Set
                Me.answer2QuestionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer2ResponseId() As String
            Get
                Return Me.answer2ResponseIdField
            End Get
            Set
                Me.answer2ResponseIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer3QuestionId() As String
            Get
                Return Me.answer3QuestionIdField
            End Get
            Set
                Me.answer3QuestionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer3ResponseId() As String
            Get
                Return Me.answer3ResponseIdField
            End Get
            Set
                Me.answer3ResponseIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer4QuestionId() As String
            Get
                Return Me.answer4QuestionIdField
            End Get
            Set
                Me.answer4QuestionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer4ResponseId() As String
            Get
                Return Me.answer4ResponseIdField
            End Get
            Set
                Me.answer4ResponseIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer5QuestionId() As String
            Get
                Return Me.answer5QuestionIdField
            End Get
            Set
                Me.answer5QuestionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer5ResponseId() As String
            Get
                Return Me.answer5ResponseIdField
            End Get
            Set
                Me.answer5ResponseIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer6QuestionId() As String
            Get
                Return Me.answer6QuestionIdField
            End Get
            Set
                Me.answer6QuestionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer6ResponseId() As String
            Get
                Return Me.answer6ResponseIdField
            End Get
            Set
                Me.answer6ResponseIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property quizid() As String
            Get
                Return Me.quizidField
            End Get
            Set
                Me.quizidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property transid() As String
            Get
                Return Me.transidField
            End Get
            Set
                Me.transidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://V001.replyobjects.soap.penleyinc.com")>  _
    Partial Public Class KBAQuestion
        
        Private answer1idField As String
        
        Private answer1textField As String
        
        Private answer2idField As String
        
        Private answer2textField As String
        
        Private answer3idField As String
        
        Private answer3textField As String
        
        Private answer4idField As String
        
        Private answer4textField As String
        
        Private answer5idField As String
        
        Private answer5textField As String
        
        Private answer6idField As String
        
        Private answer6textField As String
        
        Private idField As String
        
        Private questiontextField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer1id() As String
            Get
                Return Me.answer1idField
            End Get
            Set
                Me.answer1idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer1text() As String
            Get
                Return Me.answer1textField
            End Get
            Set
                Me.answer1textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer2id() As String
            Get
                Return Me.answer2idField
            End Get
            Set
                Me.answer2idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer2text() As String
            Get
                Return Me.answer2textField
            End Get
            Set
                Me.answer2textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer3id() As String
            Get
                Return Me.answer3idField
            End Get
            Set
                Me.answer3idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer3text() As String
            Get
                Return Me.answer3textField
            End Get
            Set
                Me.answer3textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer4id() As String
            Get
                Return Me.answer4idField
            End Get
            Set
                Me.answer4idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer4text() As String
            Get
                Return Me.answer4textField
            End Get
            Set
                Me.answer4textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer5id() As String
            Get
                Return Me.answer5idField
            End Get
            Set
                Me.answer5idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer5text() As String
            Get
                Return Me.answer5textField
            End Get
            Set
                Me.answer5textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer6id() As String
            Get
                Return Me.answer6idField
            End Get
            Set
                Me.answer6idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property answer6text() As String
            Get
                Return Me.answer6textField
            End Get
            Set
                Me.answer6textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property questiontext() As String
            Get
                Return Me.questiontextField
            End Get
            Set
                Me.questiontextField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://V001.replyobjects.soap.penleyinc.com")>  _
    Partial Public Class KBAQuestions
        
        Private kBAQuestion1Field As KBAQuestion
        
        Private kBAQuestion2Field As KBAQuestion
        
        Private kBAQuestion3Field As KBAQuestion
        
        Private kBAQuestion4Field As KBAQuestion
        
        Private kBAQuestion5Field As KBAQuestion
        
        Private kBAQuestion6Field As KBAQuestion
        
        Private kBAQuestion7Field As KBAQuestion
        
        Private kBAQuestion8Field As KBAQuestion
        
        Private kBAQuestion9Field As KBAQuestion
        
        Private quizidField As String
        
        Private quizremainField As String
        
        Private quiztimeField As String
        
        Private transidField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion1() As KBAQuestion
            Get
                Return Me.kBAQuestion1Field
            End Get
            Set
                Me.kBAQuestion1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion2() As KBAQuestion
            Get
                Return Me.kBAQuestion2Field
            End Get
            Set
                Me.kBAQuestion2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion3() As KBAQuestion
            Get
                Return Me.kBAQuestion3Field
            End Get
            Set
                Me.kBAQuestion3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion4() As KBAQuestion
            Get
                Return Me.kBAQuestion4Field
            End Get
            Set
                Me.kBAQuestion4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion5() As KBAQuestion
            Get
                Return Me.kBAQuestion5Field
            End Get
            Set
                Me.kBAQuestion5Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion6() As KBAQuestion
            Get
                Return Me.kBAQuestion6Field
            End Get
            Set
                Me.kBAQuestion6Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion7() As KBAQuestion
            Get
                Return Me.kBAQuestion7Field
            End Get
            Set
                Me.kBAQuestion7Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion8() As KBAQuestion
            Get
                Return Me.kBAQuestion8Field
            End Get
            Set
                Me.kBAQuestion8Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property KBAQuestion9() As KBAQuestion
            Get
                Return Me.kBAQuestion9Field
            End Get
            Set
                Me.kBAQuestion9Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property quizid() As String
            Get
                Return Me.quizidField
            End Get
            Set
                Me.quizidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property quizremain() As String
            Get
                Return Me.quizremainField
            End Get
            Set
                Me.quizremainField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property quiztime() As String
            Get
                Return Me.quiztimeField
            End Get
            Set
                Me.quiztimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property transid() As String
            Get
                Return Me.transidField
            End Get
            Set
                Me.transidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://V001.queryobjects.soap.penleyinc.com")>  _
    Partial Public Class KBAPerson
        
        Private addressField As String
        
        Private cityField As String
        
        Private dobField As String
        
        Private firstnameField As String
        
        Private lastnameField As String
        
        Private ssnField As String
        
        Private stateField As String
        
        Private zipField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property city() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property dob() As String
            Get
                Return Me.dobField
            End Get
            Set
                Me.dobField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set
                Me.firstnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set
                Me.lastnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property ssn() As String
            Get
                Return Me.ssnField
            End Get
            Set
                Me.ssnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property state() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property zip() As String
            Get
                Return Me.zipField
            End Get
            Set
                Me.zipField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub kbaQuestionCompletedEventHandler(ByVal sender As Object, ByVal e As kbaQuestionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class kbaQuestionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As KBAQuestions
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),KBAQuestions)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub kbaAnswerCompletedEventHandler(ByVal sender As Object, ByVal e As kbaAnswerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class kbaAnswerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As KBADecision
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),KBADecision)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub kbaAuthenticateCompletedEventHandler(ByVal sender As Object, ByVal e As kbaAuthenticateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class kbaAuthenticateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub kbaQuestionV002CompletedEventHandler(ByVal sender As Object, ByVal e As kbaQuestionV002CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class kbaQuestionV002CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As KBAQuestions
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),KBAQuestions)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub kbaAnswerV002CompletedEventHandler(ByVal sender As Object, ByVal e As kbaAnswerV002CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class kbaAnswerV002CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As KBADecision1
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),KBADecision1)
            End Get
        End Property
    End Class
End Namespace
