'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
'
Namespace AFCU17.LoanScoreService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="LoanScore_MSSOAP_HTTP_Binding", [Namespace]:="http://americafirst.com/LoanScore")>  _
    Partial Public Class LoanScore_MSSOAP_HTTP_ServiceWse
        Inherits Microsoft.Web.Services3.WebServicesClientProtocol
        
        Private inquireLoanScoreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private maintainLoanScoreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.LoansPQWSWrappers_AFCU17_LoanScoreService_LoanScore_MSSOAP_HTTP_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event inquireLoanScoreCompleted As inquireLoanScoreCompletedEventHandler
        
        '''<remarks/>
        Public Event maintainLoanScoreCompleted As maintainLoanScoreCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function inquireLoanScore(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")> ByVal inquireLoanScoreRequest As InquireLoanScoreRequest) As <System.Xml.Serialization.XmlElementAttribute("inquireLoanScoreResponse", [Namespace]:="http://www.americafirst.com/20070315/LoanScore")> InquireLoanScoreResponse
            Dim results() As Object = Me.Invoke("inquireLoanScore", New Object() {inquireLoanScoreRequest})
            Return CType(results(0),InquireLoanScoreResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub inquireLoanScoreAsync(ByVal inquireLoanScoreRequest As InquireLoanScoreRequest)
            Me.inquireLoanScoreAsync(inquireLoanScoreRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub inquireLoanScoreAsync(ByVal inquireLoanScoreRequest As InquireLoanScoreRequest, ByVal userState As Object)
            If (Me.inquireLoanScoreOperationCompleted Is Nothing) Then
                Me.inquireLoanScoreOperationCompleted = AddressOf Me.OninquireLoanScoreOperationCompleted
            End If
            Me.InvokeAsync("inquireLoanScore", New Object() {inquireLoanScoreRequest}, Me.inquireLoanScoreOperationCompleted, userState)
        End Sub
        
        Private Sub OninquireLoanScoreOperationCompleted(ByVal arg As Object)
            If (Not (Me.inquireLoanScoreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent inquireLoanScoreCompleted(Me, New inquireLoanScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function maintainLoanScore(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")> ByVal maintainLoanScoreRequest As MaintainLoanScoreRequest) As <System.Xml.Serialization.XmlElementAttribute("maintainLoanScoreResponse", [Namespace]:="http://www.americafirst.com/20070315/LoanScore")> MaintainLoanScoreResponse
            Dim results() As Object = Me.Invoke("maintainLoanScore", New Object() {maintainLoanScoreRequest})
            Return CType(results(0),MaintainLoanScoreResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub maintainLoanScoreAsync(ByVal maintainLoanScoreRequest As MaintainLoanScoreRequest)
            Me.maintainLoanScoreAsync(maintainLoanScoreRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub maintainLoanScoreAsync(ByVal maintainLoanScoreRequest As MaintainLoanScoreRequest, ByVal userState As Object)
            If (Me.maintainLoanScoreOperationCompleted Is Nothing) Then
                Me.maintainLoanScoreOperationCompleted = AddressOf Me.OnmaintainLoanScoreOperationCompleted
            End If
            Me.InvokeAsync("maintainLoanScore", New Object() {maintainLoanScoreRequest}, Me.maintainLoanScoreOperationCompleted, userState)
        End Sub
        
        Private Sub OnmaintainLoanScoreOperationCompleted(ByVal arg As Object)
            If (Not (Me.maintainLoanScoreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent maintainLoanScoreCompleted(Me, New maintainLoanScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="LoanScore_MSSOAP_HTTP_Binding", [Namespace]:="http://americafirst.com/LoanScore")>  _
    Partial Public Class LoanScore_MSSOAP_HTTP_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private inquireLoanScoreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private maintainLoanScoreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LoansPQ.WebServices.Wrappers.My.MySettings.Default.LoansPQWSWrappers_AFCU17_LoanScoreService_LoanScore_MSSOAP_HTTP_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event inquireLoanScoreCompleted As inquireLoanScoreCompletedEventHandler
        
        '''<remarks/>
        Public Event maintainLoanScoreCompleted As maintainLoanScoreCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function inquireLoanScore(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")> ByVal inquireLoanScoreRequest As InquireLoanScoreRequest) As <System.Xml.Serialization.XmlElementAttribute("inquireLoanScoreResponse", [Namespace]:="http://www.americafirst.com/20070315/LoanScore")> InquireLoanScoreResponse
            Dim results() As Object = Me.Invoke("inquireLoanScore", New Object() {inquireLoanScoreRequest})
            Return CType(results(0),InquireLoanScoreResponse)
        End Function
        
        '''<remarks/>
        Public Function BegininquireLoanScore(ByVal inquireLoanScoreRequest As InquireLoanScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("inquireLoanScore", New Object() {inquireLoanScoreRequest}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndinquireLoanScore(ByVal asyncResult As System.IAsyncResult) As InquireLoanScoreResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),InquireLoanScoreResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub inquireLoanScoreAsync(ByVal inquireLoanScoreRequest As InquireLoanScoreRequest)
            Me.inquireLoanScoreAsync(inquireLoanScoreRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub inquireLoanScoreAsync(ByVal inquireLoanScoreRequest As InquireLoanScoreRequest, ByVal userState As Object)
            If (Me.inquireLoanScoreOperationCompleted Is Nothing) Then
                Me.inquireLoanScoreOperationCompleted = AddressOf Me.OninquireLoanScoreOperationCompleted
            End If
            Me.InvokeAsync("inquireLoanScore", New Object() {inquireLoanScoreRequest}, Me.inquireLoanScoreOperationCompleted, userState)
        End Sub
        
        Private Sub OninquireLoanScoreOperationCompleted(ByVal arg As Object)
            If (Not (Me.inquireLoanScoreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent inquireLoanScoreCompleted(Me, New inquireLoanScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function maintainLoanScore(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")> ByVal maintainLoanScoreRequest As MaintainLoanScoreRequest) As <System.Xml.Serialization.XmlElementAttribute("maintainLoanScoreResponse", [Namespace]:="http://www.americafirst.com/20070315/LoanScore")> MaintainLoanScoreResponse
            Dim results() As Object = Me.Invoke("maintainLoanScore", New Object() {maintainLoanScoreRequest})
            Return CType(results(0),MaintainLoanScoreResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginmaintainLoanScore(ByVal maintainLoanScoreRequest As MaintainLoanScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("maintainLoanScore", New Object() {maintainLoanScoreRequest}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndmaintainLoanScore(ByVal asyncResult As System.IAsyncResult) As MaintainLoanScoreResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),MaintainLoanScoreResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub maintainLoanScoreAsync(ByVal maintainLoanScoreRequest As MaintainLoanScoreRequest)
            Me.maintainLoanScoreAsync(maintainLoanScoreRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub maintainLoanScoreAsync(ByVal maintainLoanScoreRequest As MaintainLoanScoreRequest, ByVal userState As Object)
            If (Me.maintainLoanScoreOperationCompleted Is Nothing) Then
                Me.maintainLoanScoreOperationCompleted = AddressOf Me.OnmaintainLoanScoreOperationCompleted
            End If
            Me.InvokeAsync("maintainLoanScore", New Object() {maintainLoanScoreRequest}, Me.maintainLoanScoreOperationCompleted, userState)
        End Sub
        
        Private Sub OnmaintainLoanScoreOperationCompleted(ByVal arg As Object)
            If (Not (Me.maintainLoanScoreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent maintainLoanScoreCompleted(Me, New maintainLoanScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class InquireLoanScoreRequest
        
        Private headerField As AFCUHeaderRequest
        
        Private requestField As InquireRequest
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderRequest
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property request() As InquireRequest
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Partial Public Class AFCUHeaderRequest
        
        Private processingDateField As Date
        
        Private companyIDField As String
        
        Private channelIDField As String
        
        Private branchIDField As String
        
        Private tellerIDField As String
        
        Private employeeIDField As String
        
        Private workstationIDField As String
        
        Private transactionIDField As String
        
        Private transactionRetryField As Boolean
        
        Private transactionRetryFieldSpecified As Boolean
        
        Private offlineIndicatorField As Boolean
        
        Private offlineIndicatorFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
        Public Property processingDate() As Date
            Get
                Return Me.processingDateField
            End Get
            Set
                Me.processingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property companyID() As String
            Get
                Return Me.companyIDField
            End Get
            Set
                Me.companyIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property channelID() As String
            Get
                Return Me.channelIDField
            End Get
            Set
                Me.channelIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property branchID() As String
            Get
                Return Me.branchIDField
            End Get
            Set
                Me.branchIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property tellerID() As String
            Get
                Return Me.tellerIDField
            End Get
            Set
                Me.tellerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property employeeID() As String
            Get
                Return Me.employeeIDField
            End Get
            Set
                Me.employeeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property workstationID() As String
            Get
                Return Me.workstationIDField
            End Get
            Set
                Me.workstationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger")>  _
        Public Property transactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property transactionRetry() As Boolean
            Get
                Return Me.transactionRetryField
            End Get
            Set
                Me.transactionRetryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property transactionRetrySpecified() As Boolean
            Get
                Return Me.transactionRetryFieldSpecified
            End Get
            Set
                Me.transactionRetryFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property offlineIndicator() As Boolean
            Get
                Return Me.offlineIndicatorField
            End Get
            Set
                Me.offlineIndicatorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property offlineIndicatorSpecified() As Boolean
            Get
                Return Me.offlineIndicatorFieldSpecified
            End Get
            Set
                Me.offlineIndicatorFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class MaintainLoanScoreResponse
        
        Private headerField As AFCUHeaderResponse
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderResponse
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Partial Public Class AFCUHeaderResponse
        
        Private systemResponseField() As SystemResponse
        
        Private resultField As Result
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("systemResponse", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property systemResponse() As SystemResponse()
            Get
                Return Me.systemResponseField
            End Get
            Set
                Me.systemResponseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property result() As Result
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Partial Public Class SystemResponse
        
        Private responseSourceField As String
        
        Private responseCodeField As String
        
        Private reasonCodeField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property responseSource() As String
            Get
                Return Me.responseSourceField
            End Get
            Set
                Me.responseSourceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property reasonCode() As String
            Get
                Return Me.reasonCodeField
            End Get
            Set
                Me.reasonCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/AFCUHeader")>  _
    Public Enum Result
        
        '''<remarks/>
        success
        
        '''<remarks/>
        failure
        
        '''<remarks/>
        warning
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class MaintainLoanScoreDetails
        
        Private accountIDField As Long
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property accountID() As Long
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("legacy", GetType(LoanScoreDetailsLegacy), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("score", GetType(LoanScoreDetails), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class LoanScoreDetailsLegacy
        
        Private scoreField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property score() As String
            Get
                Return Me.scoreField
            End Get
            Set
                Me.scoreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class LoanScoreDetails
        
        Private lastLoanDecisionField As String
        
        Private lastLoanYearField As String
        
        Private creditRatingField As String
        
        Private lastCreditBureauYearField As String
        
        Private repaymentField As Repayment
        
        Private lastDelinquencyDateField As String
        
        Private disclosureField As Disclosure
        
        Private isMinorField As Boolean
        
        Private itemsField() As String
        
        Private itemsElementNameField() As ItemsChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lastLoanDecision() As String
            Get
                Return Me.lastLoanDecisionField
            End Get
            Set
                Me.lastLoanDecisionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lastLoanYear() As String
            Get
                Return Me.lastLoanYearField
            End Get
            Set
                Me.lastLoanYearField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property creditRating() As String
            Get
                Return Me.creditRatingField
            End Get
            Set
                Me.creditRatingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lastCreditBureauYear() As String
            Get
                Return Me.lastCreditBureauYearField
            End Get
            Set
                Me.lastCreditBureauYearField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property repayment() As Repayment
            Get
                Return Me.repaymentField
            End Get
            Set
                Me.repaymentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lastDelinquencyDate() As String
            Get
                Return Me.lastDelinquencyDateField
            End Get
            Set
                Me.lastDelinquencyDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property disclosure() As Disclosure
            Get
                Return Me.disclosureField
            End Get
            Set
                Me.disclosureField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property isMinor() As Boolean
            Get
                Return Me.isMinorField
            End Get
            Set
                Me.isMinorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("collection", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("fico", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger"),  _
         System.Xml.Serialization.XmlElementAttribute("loanActionDate", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger"),  _
         System.Xml.Serialization.XmlElementAttribute("pointScore", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="nonNegativeInteger"),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Public Enum Repayment
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("No Previous")>  _
        NoPrevious
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Current 1-29 days")>  _
        Current129days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("30 days")>  _
        Item30days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("60 days")>  _
        Item60days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("90 days")>  _
        Item90days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("120 days")>  _
        Item120days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("150 days")>  _
        Item150days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("180 days")>  _
        Item180days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("210 days")>  _
        Item210days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("240 days")>  _
        Item240days
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("270 days")>  _
        Item270days
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Public Enum Disclosure
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("No Plan Signed")>  _
        NoPlanSigned
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Loan Liner Plan and Disclosure Signed")>  _
        LoanLinerPlanandDisclosureSigned
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Vantage Plan and Disclosure Signed")>  _
        VantagePlanandDisclosureSigned
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore", IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":collection")>  _
        collection
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":fico")>  _
        fico
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":loanActionDate")>  _
        loanActionDate
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":pointScore")>  _
        pointScore
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class MaintainLoanScoreRequest
        
        Private headerField As AFCUHeaderRequest
        
        Private requestField As MaintainLoanScoreDetails
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderRequest
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property request() As MaintainLoanScoreDetails
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class InquireLoanScoreWarning
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class InquireLSResponse
        
        Private accountIDField As Long
        
        Private itemField As Object
        
        Private legacyField As LoanScoreDetailsLegacy
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property accountID() As Long
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("score", GetType(LoanScoreDetails), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("warningMsg", GetType(InquireLoanScoreWarning), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property legacy() As LoanScoreDetailsLegacy
            Get
                Return Me.legacyField
            End Get
            Set
                Me.legacyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class InquireLoanScoreResponse
        
        Private headerField As AFCUHeaderResponse
        
        Private dataField As InquireLSResponse
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property header() As AFCUHeaderResponse
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property data() As InquireLSResponse
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.americafirst.com/20070315/LoanScore")>  _
    Partial Public Class InquireRequest
        
        Private accountIDField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property accountID() As Long
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub inquireLoanScoreCompletedEventHandler(ByVal sender As Object, ByVal e As inquireLoanScoreCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class inquireLoanScoreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InquireLoanScoreResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InquireLoanScoreResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub maintainLoanScoreCompletedEventHandler(ByVal sender As Object, ByVal e As maintainLoanScoreCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class maintainLoanScoreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MaintainLoanScoreResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MaintainLoanScoreResponse)
            End Get
        End Property
    End Class
End Namespace
